// Copyright (c) 2026 webOS Phoenix contributors
// SPDX-License-Identifier: Apache-2.0
//
// Generated by tools/gen-assistant-bird.py from art/assistant-bird/bird.json:
// edit that and run the tool; CI checks this file is up to date.

/* eslint-disable */
export const BIRD = {
 "about": "The Phoenix Assistant's character (docs/ASSISTANT-CHARACTER.md): original art for Phoenix, Apache-2.0. The one source of both renderers: tools/gen-assistant-bird.py writes shell/qml/Phoenix/Shell/AssistantBirdData.js and apps/assistant/src/bird/birdData.ts and bird.generated.css from it. Coordinates are in a 400 x 440 drawing; angles in degrees (positive clockwise); times in ms at normal speed.",
 "viewBox": [
  400,
  440
 ],
 "colors": {
  "ink": "#141414",
  "belly": "#FFFFFF",
  "eye": "#FFFFFF",
  "gold": "#F2B705",
  "flame": "#FFE066",
  "flameCore": "#FFF6C8",
  "beakDark": "#E0A800",
  "beak": "#FFD23F",
  "beakHighlight": "#FFF0A8",
  "nostril": "#A87500",
  "mouth": "#7A2E00",
  "tongue": "#E86A5A",
  "snore": "#9A9A9A",
  "sweat": "#7FC6E8"
 },
 "parts": {
  "shadow": {
   "d": "M105 412 A100 11 0 1 0 305 412 A100 11 0 1 0 105 412 Z",
   "fill": "ink",
   "opacity": 0.14,
   "bbox": [
    105.0,
    401.0,
    305.0,
    423.0
   ]
  },
  "tail": {
   "d": "M118 290 C 70 278 40 308 30 344 C 62 326 84 328 104 338 C 82 350 70 368 70 388 C 98 364 122 356 142 354 Z",
   "fill": "gold",
   "bbox": [
    30.0,
    287.31,
    142.0,
    388.0
   ]
  },
  "tailInner": {
   "d": "M126 304 C 92 300 70 322 62 348 C 86 334 104 336 122 344 Z",
   "fill": "flame",
   "bbox": [
    62.0,
    303.53,
    126.0,
    348.0
   ]
  },
  "crest": {
   "d": "M0 6 C -18 6 -26 -8 -20 -22 C -18 -28 -14 -32 -12 -36 C -10 -28 -6 -24 -4 -24 C -8 -36 -2 -50 6 -60 C 6 -48 12 -40 14 -34 C 16 -38 18 -42 22 -44 C 26 -30 24 -10 14 0 C 10 4 4 6 0 6 Z",
   "fill": "gold",
   "bbox": [
    -21.97,
    -60.0,
    23.93,
    6.0
   ]
  },
  "crestInner": {
   "d": "M2 4 C -8 4 -12 -6 -8 -16 C -6 -12 -4 -10 -2 -12 C -4 -22 0 -32 6 -38 C 8 -28 12 -22 12 -14 C 14 -6 10 4 2 4 Z",
   "fill": "flame",
   "bbox": [
    -9.53,
    -38.0,
    12.51,
    4.0
   ]
  },
  "crestCore": {
   "d": "M3 2 C -2 2 -4 -4 -2 -10 C 0 -8 2 -8 3 -10 C 3 -14 5 -18 7 -20 C 8 -14 9 -10 8 -5 C 8 -1 6 2 3 2 Z",
   "fill": "flameCore",
   "bbox": [
    -2.77,
    -20.0,
    8.41,
    2.0
   ]
  },
  "footL": {
   "d": "M162 386 Q150 404 136 408 Q160 414 182 400 Z",
   "fill": "gold",
   "bbox": [
    136.0,
    386.0,
    182.0,
    409.8
   ]
  },
  "footR": {
   "d": "M248 386 Q260 404 274 408 Q250 414 228 400 Z",
   "fill": "gold",
   "bbox": [
    228.0,
    386.0,
    274.0,
    409.8
   ]
  },
  "body": {
   "d": "M205 92 C 290 92 322 184 318 264 C 314 344 268 392 205 392 C 136 392 100 342 102 262 C 104 176 130 92 205 92 Z",
   "fill": "ink",
   "bbox": [
    101.92,
    92.0,
    318.33,
    392.0
   ]
  },
  "belly": {
   "d": "M205 236 C 252 236 276 280 272 324 C 268 362 242 386 205 386 C 168 386 142 362 138 324 C 134 280 158 236 205 236 Z",
   "fill": "belly",
   "bbox": [
    137.57,
    236.0,
    272.43,
    386.0
   ]
  },
  "wingL": {
   "d": "M110 224 C 74 254 64 306 80 338 C 100 318 112 286 116 254 Z",
   "fill": "ink",
   "bbox": [
    72.62,
    224.0,
    116.0,
    338.0
   ]
  },
  "wingTipL": {
   "d": "M80 338 C 76 326 76 316 80 306 C 86 318 90 326 88 334 Z",
   "fill": "gold",
   "bbox": [
    77.0,
    306.0,
    88.52,
    338.0
   ]
  },
  "wingR": {
   "d": "M300 224 C 336 254 346 306 330 338 C 310 318 298 286 294 254 Z",
   "fill": "ink",
   "bbox": [
    294.0,
    224.0,
    337.38,
    338.0
   ]
  },
  "wingTipR": {
   "d": "M330 338 C 334 326 334 316 330 306 C 324 318 320 326 322 334 Z",
   "fill": "gold",
   "bbox": [
    321.48,
    306.0,
    333.0,
    338.0
   ]
  },
  "eye": {
   "d": "M-10 0 A10 10 0 1 0 10 0 A10 10 0 1 0 -10 0 Z",
   "fill": "eye",
   "bbox": [
    -10.0,
    -10.0,
    10.0,
    10.0
   ]
  },
  "happyL": {
   "d": "M160 188 Q174 160 188 188",
   "stroke": "eye",
   "width": 11,
   "bbox": [
    160.0,
    174.0,
    188.0,
    188.0
   ]
  },
  "happyR": {
   "d": "M224 188 Q238 160 252 188",
   "stroke": "eye",
   "width": 11,
   "bbox": [
    224.0,
    174.0,
    252.0,
    188.0
   ]
  },
  "sleepyL": {
   "d": "M160 180 Q174 192 188 180",
   "stroke": "eye",
   "width": 8,
   "bbox": [
    160.0,
    180.0,
    188.0,
    186.0
   ]
  },
  "sleepyR": {
   "d": "M224 180 Q238 192 252 180",
   "stroke": "eye",
   "width": 8,
   "bbox": [
    224.0,
    180.0,
    252.0,
    186.0
   ]
  },
  "lidFocusL": {
   "d": "M150 150 L196 166 L196 174 L150 174 Z",
   "fill": "ink",
   "bbox": [
    150.0,
    150.0,
    196.0,
    174.0
   ]
  },
  "lidFocusR": {
   "d": "M262 150 L216 166 L216 174 L262 174 Z",
   "fill": "ink",
   "bbox": [
    216.0,
    150.0,
    262.0,
    174.0
   ]
  },
  "lidThinkL": {
   "d": "M154 186 Q174 174 194 186 L194 204 L154 204 Z",
   "fill": "ink",
   "bbox": [
    154.0,
    180.0,
    194.0,
    204.0
   ]
  },
  "lidThinkR": {
   "d": "M218 182 Q238 168 258 180 L258 204 L218 204 Z",
   "fill": "ink",
   "bbox": [
    218.0,
    174.46,
    258.0,
    204.0
   ]
  },
  "lidAskR": {
   "d": "M218 156 L262 166 L262 172 L218 172 Z",
   "fill": "ink",
   "bbox": [
    218.0,
    156.0,
    262.0,
    172.0
   ]
  },
  "lidConfusedL": {
   "d": "M154 146 L196 158 L196 160 L154 152 Z",
   "fill": "ink",
   "bbox": [
    154.0,
    146.0,
    196.0,
    160.0
   ]
  },
  "jaw": {
   "d": "M186 220 L236 220 L211 262 Z",
   "fill": "beakDark",
   "bbox": [
    186.0,
    220.0,
    236.0,
    262.0
   ]
  },
  "mouth": {
   "d": "M192 220 L230 220 L211 248 Z",
   "fill": "mouth",
   "bbox": [
    192.0,
    220.0,
    230.0,
    248.0
   ]
  },
  "tongue": {
   "d": "M203 234 A8 5 0 1 0 219 234 A8 5 0 1 0 203 234 Z",
   "fill": "tongue",
   "bbox": [
    203.0,
    229.0,
    219.0,
    239.0
   ]
  },
  "grinJaw": {
   "d": "M184 216 Q211 264 238 216 Z",
   "fill": "beakDark",
   "bbox": [
    184.0,
    216.0,
    238.0,
    240.0
   ]
  },
  "grinMouth": {
   "d": "M192 216 Q211 250 230 216 Z",
   "fill": "mouth",
   "bbox": [
    192.0,
    216.0,
    230.0,
    233.0
   ]
  },
  "upperBeak": {
   "d": "M180 202 Q206 190 232 202 Q236 210 211 232 Q186 210 180 202 Z",
   "fill": "beak",
   "bbox": [
    180.0,
    196.0,
    232.55,
    232.0
   ]
  },
  "beakShine": {
   "d": "M188 202 Q206 195 226 202 Q206 200 188 205 Z",
   "fill": "beakHighlight",
   "bbox": [
    188.0,
    198.5,
    226.0,
    205.0
   ]
  },
  "nostrilL": {
   "d": "M197.8 205 A2.2 2.2 0 1 0 202.2 205 A2.2 2.2 0 1 0 197.8 205 Z",
   "fill": "nostril",
   "bbox": [
    197.8,
    202.8,
    202.2,
    207.2
   ]
  },
  "nostrilR": {
   "d": "M211.8 205 A2.2 2.2 0 1 0 216.2 205 A2.2 2.2 0 1 0 211.8 205 Z",
   "fill": "nostril",
   "bbox": [
    211.8,
    202.8,
    216.2,
    207.2
   ]
  },
  "snoreSmall": {
   "d": "M293 77 L309 77 L293 95 L309 95",
   "stroke": "snore",
   "width": 5,
   "bbox": [
    293.0,
    77.0,
    309.0,
    95.0
   ]
  },
  "snoreBig": {
   "d": "M320 38 L344 38 L320 64 L344 64",
   "stroke": "snore",
   "width": 6,
   "bbox": [
    320.0,
    38.0,
    344.0,
    64.0
   ]
  },
  "sparkle1": {
   "d": "M62 70 L67 86 L83 91 L67 96 L62 112 L57 96 L41 91 L57 86 Z",
   "fill": "gold",
   "bbox": [
    41.0,
    70.0,
    83.0,
    112.0
   ]
  },
  "sparkle2": {
   "d": "M344 52 L348 64 L360 68 L348 72 L344 84 L340 72 L328 68 L340 64 Z",
   "fill": "flame",
   "bbox": [
    328.0,
    52.0,
    360.0,
    84.0
   ]
  },
  "sparkle3": {
   "d": "M352 170 L355 178 L363 181 L355 184 L352 192 L349 184 L341 181 L349 178 Z",
   "fill": "gold",
   "bbox": [
    341.0,
    170.0,
    363.0,
    192.0
   ]
  },
  "ember1": {
   "d": "M286 70 A6 6 0 1 0 298 70 A6 6 0 1 0 286 70 Z",
   "fill": "gold",
   "bbox": [
    286.0,
    64.0,
    298.0,
    76.0
   ]
  },
  "ember2": {
   "d": "M310 48 A8 8 0 1 0 326 48 A8 8 0 1 0 310 48 Z",
   "fill": "flame",
   "bbox": [
    310.0,
    40.0,
    326.0,
    56.0
   ]
  },
  "ember3": {
   "d": "M338 34 A10 10 0 1 0 358 34 A10 10 0 1 0 338 34 Z",
   "fill": "gold",
   "bbox": [
    338.0,
    24.0,
    358.0,
    44.0
   ]
  },
  "ring1": {
   "d": "M330 170 Q346 208 330 246",
   "stroke": "gold",
   "width": 6,
   "bbox": [
    330.0,
    170.0,
    338.0,
    246.0
   ]
  },
  "ring2": {
   "d": "M350 152 Q374 208 350 264",
   "stroke": "gold",
   "width": 6,
   "opacity": 0.6,
   "bbox": [
    350.0,
    152.0,
    362.0,
    264.0
   ]
  },
  "ring3": {
   "d": "M370 134 Q402 208 370 282",
   "stroke": "gold",
   "width": 6,
   "opacity": 0.3,
   "bbox": [
    370.0,
    134.0,
    386.0,
    282.0
   ]
  },
  "question": {
   "d": "M310 88 Q310 68 326 68 Q342 68 342 85 Q342 97 328 102 L328 110",
   "stroke": "gold",
   "width": 11,
   "bbox": [
    310.0,
    68.0,
    342.0,
    110.0
   ]
  },
  "questionDot": {
   "d": "M321 125 A7 7 0 1 0 335 125 A7 7 0 1 0 321 125 Z",
   "fill": "gold",
   "bbox": [
    321.0,
    118.0,
    335.0,
    132.0
   ]
  },
  "sweat": {
   "d": "M300 112 Q312 132 300 142 Q288 132 300 112 Z",
   "fill": "sweat",
   "bbox": [
    294.0,
    112.0,
    306.0,
    142.0
   ]
  },
  "dot1": {
   "d": "M292 96 A8 8 0 1 0 308 96 A8 8 0 1 0 292 96 Z",
   "fill": "gold",
   "bbox": [
    292.0,
    88.0,
    308.0,
    104.0
   ]
  },
  "dot2": {
   "d": "M318 96 A8 8 0 1 0 334 96 A8 8 0 1 0 318 96 Z",
   "fill": "gold",
   "opacity": 0.7,
   "bbox": [
    318.0,
    88.0,
    334.0,
    104.0
   ]
  },
  "dot3": {
   "d": "M344 96 A8 8 0 1 0 360 96 A8 8 0 1 0 344 96 Z",
   "fill": "gold",
   "opacity": 0.4,
   "bbox": [
    344.0,
    88.0,
    360.0,
    104.0
   ]
  }
 },
 "pivots": {
  "body": [
   205,
   300
  ],
  "feet": [
   205,
   410
  ],
  "breath": [
   205,
   392
  ],
  "shadow": [
   205,
   412
  ],
  "crest": [
   206,
   102
  ],
  "wingL": [
   112,
   228
  ],
  "wingR": [
   298,
   228
  ],
  "beak": [
   206,
   214
  ],
  "jaw": [
   211,
   220
  ],
  "upperBeak": [
   211,
   202
  ],
  "rings": [
   318,
   208
  ],
  "neck": [
   206,
   250
  ],
  "eyes": [
   206,
   178
  ]
 },
 "eyes": {
  "open": {
   "L": [
    174,
    178,
    13,
    22
   ],
   "R": [
    238,
    178,
    13,
    22
   ],
   "show": 1,
   "overlays": []
  },
  "wide": {
   "L": [
    174,
    176,
    15,
    26
   ],
   "R": [
    238,
    176,
    15,
    26
   ],
   "show": 1,
   "overlays": []
  },
  "happy": {
   "L": [
    174,
    180,
    13,
    5
   ],
   "R": [
    238,
    180,
    13,
    5
   ],
   "show": 0,
   "overlays": [
    "happyL",
    "happyR"
   ]
  },
  "sleepy": {
   "L": [
    174,
    184,
    13,
    3
   ],
   "R": [
    238,
    184,
    13,
    3
   ],
   "show": 0,
   "overlays": [
    "sleepyL",
    "sleepyR"
   ]
  },
  "focus": {
   "L": [
    174,
    180,
    13,
    22
   ],
   "R": [
    238,
    180,
    13,
    22
   ],
   "show": 1,
   "overlays": [
    "lidFocusL",
    "lidFocusR"
   ]
  },
  "think": {
   "L": [
    174,
    176,
    13,
    22
   ],
   "R": [
    238,
    176,
    13,
    22
   ],
   "show": 1,
   "overlays": [
    "lidThinkL",
    "lidThinkR"
   ]
  },
  "ask": {
   "L": [
    174,
    176,
    15,
    26
   ],
   "R": [
    238,
    182,
    12,
    20
   ],
   "show": 1,
   "overlays": [
    "lidAskR"
   ]
  },
  "confused": {
   "L": [
    174,
    178,
    15,
    25
   ],
   "R": [
    238,
    184,
    10,
    16
   ],
   "show": 1,
   "overlays": [
    "lidConfusedL"
   ]
  }
 },
 "overlays": {
  "happyL": {
   "dy": 6
  },
  "happyR": {
   "dy": 6
  },
  "sleepyL": {
   "dy": -4
  },
  "sleepyR": {
   "dy": -4
  },
  "lidFocusL": {
   "dy": -18
  },
  "lidFocusR": {
   "dy": -18
  },
  "lidThinkL": {
   "dy": 18
  },
  "lidThinkR": {
   "dy": 18
  },
  "lidAskR": {
   "dy": -14
  },
  "lidConfusedL": {
   "dy": -10
  }
 },
 "beaks": {
  "closed": {
   "jaw": [
    -6,
    0.84,
    0.6667
   ],
   "mouth": [
    0.85,
    0,
    0
   ],
   "tongue": 0,
   "grin": 0,
   "upper": [
    0,
    1
   ]
  },
  "open": {
   "jaw": [
    0,
    0.92,
    0.7143
   ],
   "mouth": [
    0.8947,
    0.6429,
    1
   ],
   "tongue": 0,
   "grin": 0,
   "upper": [
    0,
    0.8
   ]
  },
  "wide": {
   "jaw": [
    0,
    1,
    1
   ],
   "mouth": [
    1,
    1,
    1
   ],
   "tongue": 1,
   "grin": 0,
   "upper": [
    -2,
    0.7333
   ]
  },
  "grin": {
   "jaw": [
    0,
    1,
    1
   ],
   "mouth": [
    1,
    1,
    0
   ],
   "tongue": 0,
   "grin": 1,
   "upper": [
    -2,
    0.7333
   ]
  }
 },
 "extras": {
  "zzz": {
   "parts": [
    "snoreSmall",
    "snoreBig"
   ],
   "motion": "float",
   "dy": -12,
   "period": 2400,
   "stagger": 600
  },
  "sparkles": {
   "parts": [
    "sparkle1",
    "sparkle2",
    "sparkle3"
   ],
   "motion": "twinkle",
   "scale": 0.55,
   "period": 900,
   "stagger": 260
  },
  "embers": {
   "parts": [
    "ember1",
    "ember2",
    "ember3"
   ],
   "motion": "float",
   "dy": -18,
   "period": 1700,
   "stagger": 420
  },
  "rings": {
   "parts": [
    "ring1",
    "ring2",
    "ring3"
   ],
   "motion": "pulse",
   "low": 0.35,
   "period": 1000,
   "stagger": 200
  },
  "question": {
   "parts": [
    "question",
    "questionDot"
   ],
   "motion": "bob",
   "dy": -5,
   "period": 1400,
   "stagger": 0
  },
  "sweat": {
   "parts": [
    "sweat"
   ],
   "motion": "float",
   "dy": 10,
   "period": 1600,
   "stagger": 0
  },
  "dots": {
   "parts": [
    "dot1",
    "dot2",
    "dot3"
   ],
   "motion": "pulse",
   "low": 0.25,
   "period": 900,
   "stagger": 180
  }
 },
 "poses": {
  "asleep": {
   "label": "Asleep",
   "eyes": "sleepy",
   "beak": "closed",
   "lift": 0,
   "tilt": 6,
   "wingL": -6,
   "wingR": 6,
   "crestScale": 0.35,
   "crestRotation": 0,
   "beakTilt": 0,
   "extras": [
    "zzz"
   ]
  },
  "hello": {
   "label": "Hello",
   "eyes": "happy",
   "beak": "grin",
   "lift": 0,
   "tilt": -3,
   "wingL": 0,
   "wingR": -128,
   "crestScale": 1.4,
   "crestRotation": 0,
   "beakTilt": 0,
   "extras": []
  },
  "idle": {
   "label": "Idle",
   "eyes": "open",
   "beak": "closed",
   "lift": 0,
   "tilt": 0,
   "wingL": 0,
   "wingR": 0,
   "crestScale": 1.4,
   "crestRotation": 0,
   "beakTilt": 0,
   "extras": []
  },
  "listening": {
   "label": "Listening",
   "eyes": "wide",
   "beak": "open",
   "lift": 0,
   "tilt": 8,
   "wingL": 18,
   "wingR": 0,
   "crestScale": 1.75,
   "crestRotation": 0,
   "beakTilt": 0,
   "extras": [
    "rings"
   ]
  },
  "thinking": {
   "label": "Thinking",
   "eyes": "think",
   "beak": "closed",
   "lift": 0,
   "tilt": -4,
   "wingL": 0,
   "wingR": 104,
   "crestScale": 1.4,
   "crestRotation": -6,
   "beakTilt": -14,
   "extras": [
    "embers"
   ]
  },
  "working": {
   "label": "Working on it",
   "eyes": "focus",
   "beak": "closed",
   "lift": 0,
   "tilt": 0,
   "wingL": 28,
   "wingR": -28,
   "crestScale": 1.85,
   "crestRotation": 0,
   "beakTilt": 0,
   "extras": [
    "dots"
   ]
  },
  "speaking": {
   "label": "Speaking",
   "eyes": "open",
   "beak": "wide",
   "lift": 0,
   "tilt": 3,
   "wingL": 0,
   "wingR": -46,
   "crestScale": 1.45,
   "crestRotation": 0,
   "beakTilt": 0,
   "extras": []
  },
  "done": {
   "label": "Done!",
   "eyes": "happy",
   "beak": "grin",
   "lift": 46,
   "tilt": 0,
   "wingL": 132,
   "wingR": -132,
   "crestScale": 2.1,
   "crestRotation": 0,
   "beakTilt": 0,
   "extras": [
    "sparkles"
   ]
  },
  "asking": {
   "label": "Asking first",
   "eyes": "ask",
   "beak": "open",
   "lift": 0,
   "tilt": -7,
   "wingL": 0,
   "wingR": -74,
   "crestScale": 1.4,
   "crestRotation": 0,
   "beakTilt": 0,
   "extras": [
    "question"
   ]
  },
  "confused": {
   "label": "Didn't get that",
   "eyes": "confused",
   "beak": "closed",
   "lift": 0,
   "tilt": 5,
   "wingL": 78,
   "wingR": -78,
   "crestScale": 1.25,
   "crestRotation": -72,
   "beakTilt": 14,
   "extras": [
    "sweat"
   ]
  },
  "proud": {
   "label": "Proud",
   "eyes": "happy",
   "beak": "closed",
   "lift": 0,
   "tilt": -6,
   "wingL": 48,
   "wingR": -48,
   "crestScale": 1.8,
   "crestRotation": 0,
   "beakTilt": 0,
   "extras": []
  },
  "shy": {
   "label": "Oops",
   "eyes": "sleepy",
   "beak": "closed",
   "lift": 0,
   "tilt": 10,
   "wingL": 96,
   "wingR": 0,
   "crestScale": 1.0,
   "crestRotation": 10,
   "beakTilt": 0,
   "extras": []
  }
 },
 "motion": {
  "transition": {
   "body": 450,
   "wings": 520,
   "crest": 450,
   "eyes": 220,
   "beak": 160,
   "extras": 260
  },
  "flicker": {
   "crest": {
    "period": 900,
    "origin": [
     0.5,
     1
    ],
    "keys": [
     [
      0,
      1,
      1,
      3,
      1
     ],
     [
      0.35,
      0.96,
      1.1,
      -4,
      1
     ],
     [
      0.7,
      1.04,
      0.95,
      5,
      1
     ],
     [
      1,
      0.98,
      1.08,
      -2,
      1
     ]
    ],
    "pivot": [
     0.98,
     6.0
    ],
    "keys4": [
     [
      0,
      1,
      1,
      3,
      1
     ],
     [
      0.35,
      0.96,
      1.1,
      -4,
      1
     ],
     [
      0.7,
      1.04,
      0.95,
      5,
      1
     ],
     [
      1,
      0.98,
      1.08,
      -2,
      1
     ]
    ]
   },
   "crestInner": {
    "period": 550,
    "origin": [
     0.5,
     1
    ],
    "keys": [
     [
      0,
      1,
      0.9,
      -5,
      0.85
     ],
     [
      0.5,
      0.92,
      1.16,
      5,
      1
     ],
     [
      1,
      1.05,
      1,
      -3,
      0.9
     ]
    ],
    "pivot": [
     1.49,
     4.0
    ],
    "keys4": [
     [
      0,
      1,
      0.9,
      -5,
      0.85
     ],
     [
      0.5,
      0.92,
      1.16,
      5,
      1
     ],
     [
      1,
      1.05,
      1,
      -3,
      0.9
     ],
     [
      1,
      1.05,
      1,
      -3,
      0.9
     ]
    ]
   },
   "crestCore": {
    "period": 350,
    "origin": [
     0.5,
     1
    ],
    "keys": [
     [
      0,
      0.9,
      0.85,
      0,
      0.7
     ],
     [
      1,
      1.08,
      1.2,
      0,
      1
     ]
    ],
    "pivot": [
     2.82,
     2.0
    ],
    "keys4": [
     [
      0,
      0.9,
      0.85,
      0,
      0.7
     ],
     [
      1,
      1.08,
      1.2,
      0,
      1
     ],
     [
      1,
      1.08,
      1.2,
      0,
      1
     ],
     [
      1,
      1.08,
      1.2,
      0,
      1
     ]
    ]
   },
   "crestGust": {
    "period": 2300,
    "origin": [
     0.5,
     1
    ],
    "keys": [
     [
      0,
      1,
      1,
      0,
      1
     ],
     [
      0.3,
      1.03,
      0.95,
      1.5,
      1
     ],
     [
      0.55,
      0.98,
      1.07,
      -2,
      1
     ],
     [
      1,
      1.01,
      0.98,
      0.5,
      1
     ]
    ],
    "pivot": [
     0.98,
     6.0
    ],
    "keys4": [
     [
      0,
      1,
      1,
      0,
      1
     ],
     [
      0.3,
      1.03,
      0.95,
      1.5,
      1
     ],
     [
      0.55,
      0.98,
      1.07,
      -2,
      1
     ],
     [
      1,
      1.01,
      0.98,
      0.5,
      1
     ]
    ]
   },
   "tail": {
    "period": 1300,
    "origin": [
     1,
     0.4
    ],
    "keys": [
     [
      0,
      1,
      1,
      -4,
      1
     ],
     [
      0.5,
      1.06,
      0.96,
      2,
      1
     ],
     [
      1,
      0.97,
      1.05,
      5,
      1
     ]
    ],
    "pivot": [
     142.0,
     327.59
    ],
    "keys4": [
     [
      0,
      1,
      1,
      -4,
      1
     ],
     [
      0.5,
      1.06,
      0.96,
      2,
      1
     ],
     [
      1,
      0.97,
      1.05,
      5,
      1
     ],
     [
      1,
      0.97,
      1.05,
      5,
      1
     ]
    ]
   },
   "tailInner": {
    "period": 800,
    "origin": [
     1,
     0.4
    ],
    "keys": [
     [
      0,
      0.95,
      1.05,
      3,
      0.85
     ],
     [
      1,
      1.06,
      0.94,
      -4,
      1
     ]
    ],
    "pivot": [
     126.0,
     321.32
    ],
    "keys4": [
     [
      0,
      0.95,
      1.05,
      3,
      0.85
     ],
     [
      1,
      1.06,
      0.94,
      -4,
      1
     ],
     [
      1,
      1.06,
      0.94,
      -4,
      1
     ],
     [
      1,
      1.06,
      0.94,
      -4,
      1
     ]
    ]
   }
  },
  "flickerKeys": "each key: [at (0..1 of the period), scale x, scale y, rotation, opacity]; played forward then back (CSS alternate), ease-in-out between keys",
  "breath": {
   "period": 3200,
   "scaleY": 1.018,
   "scaleX": 0.992
  },
  "blink": {
   "minGap": 2200,
   "maxGap": 5600,
   "close": 70,
   "hold": 40,
   "open": 110,
   "twice": 0.2
  },
  "hop": {
   "squash": [
    1.08,
    0.88
   ],
   "stretch": [
    0.94,
    1.08
   ],
   "takeoff": 90,
   "rise": 300,
   "fall": 260,
   "land": 90,
   "settle": 200
  },
  "speech": [
   [
    1,
    120
   ],
   [
    0.3,
    90
   ],
   [
    0.8,
    140
   ],
   [
    0.15,
    80
   ],
   [
    0.95,
    110
   ],
   [
    0.4,
    100
   ],
   [
    1,
    160
   ],
   [
    0.1,
    130
   ]
  ],
  "listen": [
   [
    0.6,
    180
   ],
   [
    0.2,
    140
   ],
   [
    0.9,
    220
   ],
   [
    0.35,
    160
   ],
   [
    0.75,
    200
   ],
   [
    0.1,
    260
   ]
  ],
  "level": {
   "crest": 0.22,
   "rings": 0.45
  },
  "acting": {
   "about": "Each pose's acting: a loop of keyframes per moving part (channel), played on top of the pose's values, over and over (or, with every: [min, max] ms, once now and then, after a random gap like the blink). Each key: [at (0..1 of the period), rotation, x, y, scale x, scale y], about the channel's pivot (pivots[channels[name]]; the crest's own base), trailing values left out stay at rest (0, 0, 0, 1, 1); ease-in-out between keys; 2 to 6 keys, from 0 to 1, the first and the last at rest so the loop joins up. A pose change blends from wherever the loop is over lead ms.",
   "lead": 280,
   "channels": {
    "body": "feet",
    "head": "neck",
    "eyes": "eyes",
    "lids": "eyes",
    "wingL": "wingL",
    "wingR": "wingR",
    "beak": "beak",
    "crest": null
   },
   "poses": {
    "asleep": {
     "period": 3600,
     "tracks": {
      "body": [
       [
        0
       ],
       [
        0.5,
        0,
        0,
        0,
        1.012,
        1.03
       ],
       [
        1
       ]
      ],
      "head": [
       [
        0
       ],
       [
        0.5,
        1.5,
        0,
        3
       ],
       [
        1
       ]
      ]
     },
     "steps": {
      "body": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.5,
        0,
        0,
        0,
        1.012,
        1.03
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "head": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.5,
        1.5,
        0,
        3,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ]
     }
    },
    "hello": {
     "period": 460,
     "tracks": {
      "wingR": [
       [
        0
       ],
       [
        0.28,
        -30
       ],
       [
        0.72,
        16
       ],
       [
        1
       ]
      ],
      "body": [
       [
        0
       ],
       [
        0.28,
        1.2
       ],
       [
        0.72,
        -1.2
       ],
       [
        1
       ]
      ],
      "head": [
       [
        0
       ],
       [
        0.28,
        -2.5
       ],
       [
        0.72,
        2
       ],
       [
        1
       ]
      ]
     },
     "steps": {
      "wingR": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.28,
        -30,
        0,
        0,
        1,
        1
       ],
       [
        0.72,
        16,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "body": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.28,
        1.2,
        0,
        0,
        1,
        1
       ],
       [
        0.72,
        -1.2,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "head": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.28,
        -2.5,
        0,
        0,
        1,
        1
       ],
       [
        0.72,
        2,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ]
     }
    },
    "idle": {
     "period": 2800,
     "every": [
      3000,
      7500
     ],
     "tracks": {
      "body": [
       [
        0
       ],
       [
        0.18,
        -2.2,
        -2
       ],
       [
        0.45,
        -2.2,
        -2
       ],
       [
        0.62,
        1.6,
        1.5
       ],
       [
        0.85,
        1.6,
        1.5
       ],
       [
        1
       ]
      ],
      "head": [
       [
        0
       ],
       [
        0.18,
        -2
       ],
       [
        0.45,
        -2
       ],
       [
        0.62,
        2
       ],
       [
        0.85,
        1.5
       ],
       [
        1
       ]
      ],
      "eyes": [
       [
        0
       ],
       [
        0.15,
        0,
        -7,
        -2
       ],
       [
        0.42,
        0,
        -7,
        -2
       ],
       [
        0.58,
        0,
        6,
        1
       ],
       [
        0.84,
        0,
        6,
        1
       ],
       [
        1
       ]
      ]
     },
     "steps": {
      "body": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.18,
        -2.2,
        -2,
        0,
        1,
        1
       ],
       [
        0.45,
        -2.2,
        -2,
        0,
        1,
        1
       ],
       [
        0.62,
        1.6,
        1.5,
        0,
        1,
        1
       ],
       [
        0.85,
        1.6,
        1.5,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "head": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.18,
        -2,
        0,
        0,
        1,
        1
       ],
       [
        0.45,
        -2,
        0,
        0,
        1,
        1
       ],
       [
        0.62,
        2,
        0,
        0,
        1,
        1
       ],
       [
        0.85,
        1.5,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "eyes": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.15,
        0,
        -7,
        -2,
        1,
        1
       ],
       [
        0.42,
        0,
        -7,
        -2,
        1,
        1
       ],
       [
        0.58,
        0,
        6,
        1,
        1,
        1
       ],
       [
        0.84,
        0,
        6,
        1,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ]
     }
    },
    "thinking": {
     "period": 2600,
     "tracks": {
      "head": [
       [
        0
       ],
       [
        0.22,
        -5,
        -2
       ],
       [
        0.5,
        0
       ],
       [
        0.72,
        4,
        2
       ],
       [
        1
       ]
      ],
      "wingR": [
       [
        0
       ],
       [
        0.08,
        -12
       ],
       [
        0.16,
        0
       ],
       [
        0.24,
        -12
       ],
       [
        0.32,
        0
       ],
       [
        1
       ]
      ],
      "eyes": [
       [
        0
       ],
       [
        0.12,
        0,
        5,
        -7
       ],
       [
        0.45,
        0,
        5,
        -7
       ],
       [
        0.6,
        0,
        -5,
        -6
       ],
       [
        0.88,
        0,
        -5,
        -6
       ],
       [
        1
       ]
      ],
      "beak": [
       [
        0
       ],
       [
        0.25,
        5
       ],
       [
        0.5,
        0
       ],
       [
        0.75,
        -4
       ],
       [
        1
       ]
      ]
     },
     "steps": {
      "head": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.22,
        -5,
        -2,
        0,
        1,
        1
       ],
       [
        0.5,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.72,
        4,
        2,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "wingR": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.08,
        -12,
        0,
        0,
        1,
        1
       ],
       [
        0.16,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.24,
        -12,
        0,
        0,
        1,
        1
       ],
       [
        0.32,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "eyes": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.12,
        0,
        5,
        -7,
        1,
        1
       ],
       [
        0.45,
        0,
        5,
        -7,
        1,
        1
       ],
       [
        0.6,
        0,
        -5,
        -6,
        1,
        1
       ],
       [
        0.88,
        0,
        -5,
        -6,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "beak": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.25,
        5,
        0,
        0,
        1,
        1
       ],
       [
        0.5,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.75,
        -4,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ]
     }
    },
    "working": {
     "period": 640,
     "tracks": {
      "body": [
       [
        0
       ],
       [
        0.25,
        0,
        0,
        -5,
        0.98,
        1.03
       ],
       [
        0.5
       ],
       [
        0.75,
        0,
        0,
        -5,
        0.98,
        1.03
       ],
       [
        1
       ]
      ],
      "head": [
       [
        0
       ],
       [
        0.25,
        0,
        0,
        2
       ],
       [
        0.5
       ],
       [
        0.75,
        0,
        0,
        2
       ],
       [
        1
       ]
      ],
      "wingL": [
       [
        0
       ],
       [
        0.25,
        26
       ],
       [
        0.5,
        0
       ],
       [
        0.75,
        -10
       ],
       [
        1
       ]
      ],
      "wingR": [
       [
        0
       ],
       [
        0.25,
        10
       ],
       [
        0.5,
        0
       ],
       [
        0.75,
        -26
       ],
       [
        1
       ]
      ],
      "lids": [
       [
        0
       ],
       [
        0.5,
        0,
        0,
        4
       ],
       [
        1
       ]
      ],
      "crest": [
       [
        0
       ],
       [
        0.25,
        0,
        0,
        0,
        1.06,
        1.14
       ],
       [
        0.5
       ],
       [
        0.75,
        0,
        0,
        0,
        1.06,
        1.14
       ],
       [
        1
       ]
      ]
     },
     "steps": {
      "body": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.25,
        0,
        0,
        -5,
        0.98,
        1.03
       ],
       [
        0.5,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.75,
        0,
        0,
        -5,
        0.98,
        1.03
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "head": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.25,
        0,
        0,
        2,
        1,
        1
       ],
       [
        0.5,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.75,
        0,
        0,
        2,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "wingL": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.25,
        26,
        0,
        0,
        1,
        1
       ],
       [
        0.5,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.75,
        -10,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "wingR": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.25,
        10,
        0,
        0,
        1,
        1
       ],
       [
        0.5,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.75,
        -26,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "lids": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.5,
        0,
        0,
        4,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "crest": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.25,
        0,
        0,
        0,
        1.06,
        1.14
       ],
       [
        0.5,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.75,
        0,
        0,
        0,
        1.06,
        1.14
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ]
     }
    },
    "speaking": {
     "period": 930,
     "tracks": {
      "wingR": [
       [
        0
       ],
       [
        0.13,
        -18
       ],
       [
        0.38,
        -6
       ],
       [
        0.59,
        -20
       ],
       [
        0.86,
        -8
       ],
       [
        1
       ]
      ],
      "head": [
       [
        0
       ],
       [
        0.13,
        1.5,
        0,
        3
       ],
       [
        0.38,
        0,
        0,
        1
       ],
       [
        0.59,
        -1.5,
        0,
        3
       ],
       [
        0.86,
        0,
        0,
        1
       ],
       [
        1
       ]
      ]
     },
     "steps": {
      "wingR": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.13,
        -18,
        0,
        0,
        1,
        1
       ],
       [
        0.38,
        -6,
        0,
        0,
        1,
        1
       ],
       [
        0.59,
        -20,
        0,
        0,
        1,
        1
       ],
       [
        0.86,
        -8,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "head": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.13,
        1.5,
        0,
        3,
        1,
        1
       ],
       [
        0.38,
        0,
        0,
        1,
        1,
        1
       ],
       [
        0.59,
        -1.5,
        0,
        3,
        1,
        1
       ],
       [
        0.86,
        0,
        0,
        1,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ]
     }
    },
    "done": {
     "period": 380,
     "tracks": {
      "wingL": [
       [
        0
       ],
       [
        0.5,
        -14
       ],
       [
        1
       ]
      ],
      "wingR": [
       [
        0
       ],
       [
        0.5,
        14
       ],
       [
        1
       ]
      ]
     },
     "steps": {
      "wingL": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.5,
        -14,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "wingR": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.5,
        14,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ]
     }
    },
    "asking": {
     "period": 1500,
     "tracks": {
      "head": [
       [
        0
       ],
       [
        0.3,
        -6,
        -3
       ],
       [
        0.7,
        -6,
        -3
       ],
       [
        1
       ]
      ],
      "wingR": [
       [
        0
       ],
       [
        0.15,
        12,
        0,
        0,
        1.16,
        1.06
       ],
       [
        0.35
       ],
       [
        0.55,
        12,
        0,
        0,
        1.16,
        1.06
       ],
       [
        0.75
       ],
       [
        1
       ]
      ]
     },
     "steps": {
      "head": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.3,
        -6,
        -3,
        0,
        1,
        1
       ],
       [
        0.7,
        -6,
        -3,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "wingR": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.15,
        12,
        0,
        0,
        1.16,
        1.06
       ],
       [
        0.35,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.55,
        12,
        0,
        0,
        1.16,
        1.06
       ],
       [
        0.75,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ]
     }
    },
    "confused": {
     "period": 1500,
     "tracks": {
      "wingL": [
       [
        0
       ],
       [
        0.12,
        20
       ],
       [
        0.3,
        0
       ],
       [
        0.45,
        16
       ],
       [
        0.62,
        0
       ],
       [
        1
       ]
      ],
      "wingR": [
       [
        0
       ],
       [
        0.12,
        -20
       ],
       [
        0.3,
        0
       ],
       [
        0.45,
        -16
       ],
       [
        0.62,
        0
       ],
       [
        1
       ]
      ],
      "body": [
       [
        0
       ],
       [
        0.12,
        0,
        0,
        -6
       ],
       [
        0.3
       ],
       [
        0.45,
        0,
        0,
        -5
       ],
       [
        0.62
       ],
       [
        1
       ]
      ],
      "head": [
       [
        0
       ],
       [
        0.12,
        0,
        0,
        5
       ],
       [
        0.3
       ],
       [
        0.45,
        0,
        0,
        4
       ],
       [
        0.62
       ],
       [
        1
       ]
      ],
      "crest": [
       [
        0
       ],
       [
        0.3,
        -10,
        0,
        0,
        0.95,
        0.8
       ],
       [
        0.8,
        -14,
        0,
        0,
        0.92,
        0.76
       ],
       [
        1
       ]
      ]
     },
     "steps": {
      "wingL": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.12,
        20,
        0,
        0,
        1,
        1
       ],
       [
        0.3,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.45,
        16,
        0,
        0,
        1,
        1
       ],
       [
        0.62,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "wingR": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.12,
        -20,
        0,
        0,
        1,
        1
       ],
       [
        0.3,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.45,
        -16,
        0,
        0,
        1,
        1
       ],
       [
        0.62,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "body": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.12,
        0,
        0,
        -6,
        1,
        1
       ],
       [
        0.3,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.45,
        0,
        0,
        -5,
        1,
        1
       ],
       [
        0.62,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "head": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.12,
        0,
        0,
        5,
        1,
        1
       ],
       [
        0.3,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.45,
        0,
        0,
        4,
        1,
        1
       ],
       [
        0.62,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "crest": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.3,
        -10,
        0,
        0,
        0.95,
        0.8
       ],
       [
        0.8,
        -14,
        0,
        0,
        0.92,
        0.76
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ]
     }
    },
    "proud": {
     "period": 1200,
     "tracks": {
      "body": [
       [
        0
       ],
       [
        0.18,
        0,
        0,
        0,
        1.05,
        0.95
       ],
       [
        0.4,
        0,
        0,
        -9,
        0.98,
        1.05
       ],
       [
        0.62,
        0,
        0,
        0,
        1.06,
        1.03
       ],
       [
        0.85,
        0,
        0,
        0,
        1.03,
        1.01
       ],
       [
        1
       ]
      ],
      "head": [
       [
        0
       ],
       [
        0.4,
        0,
        0,
        -3
       ],
       [
        0.62
       ],
       [
        1
       ]
      ],
      "crest": [
       [
        0
       ],
       [
        0.4,
        0,
        0,
        0,
        1.08,
        1.2
       ],
       [
        1
       ]
      ]
     },
     "steps": {
      "body": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.18,
        0,
        0,
        0,
        1.05,
        0.95
       ],
       [
        0.4,
        0,
        0,
        -9,
        0.98,
        1.05
       ],
       [
        0.62,
        0,
        0,
        0,
        1.06,
        1.03
       ],
       [
        0.85,
        0,
        0,
        0,
        1.03,
        1.01
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "head": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.4,
        0,
        0,
        -3,
        1,
        1
       ],
       [
        0.62,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "crest": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.4,
        0,
        0,
        0,
        1.08,
        1.2
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ]
     }
    },
    "shy": {
     "period": 2200,
     "tracks": {
      "wingL": [
       [
        0
       ],
       [
        0.18,
        52
       ],
       [
        0.5,
        52
       ],
       [
        0.62,
        -6
       ],
       [
        0.7,
        0
       ],
       [
        1
       ]
      ],
      "head": [
       [
        0
       ],
       [
        0.18,
        -6,
        -5,
        5
       ],
       [
        0.5,
        -6,
        -5,
        5
       ],
       [
        0.64,
        1,
        1,
        0
       ],
       [
        1
       ]
      ],
      "body": [
       [
        0
       ],
       [
        0.18,
        0,
        0,
        0,
        1.03,
        0.95
       ],
       [
        0.5,
        0,
        0,
        0,
        1.03,
        0.95
       ],
       [
        0.66
       ],
       [
        1
       ]
      ],
      "eyes": [
       [
        0
       ],
       [
        0.6
       ],
       [
        0.7,
        0,
        4
       ],
       [
        0.9,
        0,
        4
       ],
       [
        1
       ]
      ]
     },
     "steps": {
      "wingL": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.18,
        52,
        0,
        0,
        1,
        1
       ],
       [
        0.5,
        52,
        0,
        0,
        1,
        1
       ],
       [
        0.62,
        -6,
        0,
        0,
        1,
        1
       ],
       [
        0.7,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "head": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.18,
        -6,
        -5,
        5,
        1,
        1
       ],
       [
        0.5,
        -6,
        -5,
        5,
        1,
        1
       ],
       [
        0.64,
        1,
        1,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "body": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.18,
        0,
        0,
        0,
        1.03,
        0.95
       ],
       [
        0.5,
        0,
        0,
        0,
        1.03,
        0.95
       ],
       [
        0.66,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ],
      "eyes": [
       [
        0,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.6,
        0,
        0,
        0,
        1,
        1
       ],
       [
        0.7,
        0,
        4,
        0,
        1,
        1
       ],
       [
        0.9,
        0,
        4,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ],
       [
        1,
        0,
        0,
        0,
        1,
        1
       ]
      ]
     }
    }
   },
   "pivot": {
    "body": [
     205,
     410
    ],
    "head": [
     206,
     250
    ],
    "eyes": [
     206,
     178
    ],
    "lids": [
     206,
     178
    ],
    "wingL": [
     112,
     228
    ],
    "wingR": [
     298,
     228
    ],
    "beak": [
     206,
     214
    ],
    "crest": [
     0,
     0
    ]
   }
  }
 }
} as const;

export type BirdPose = keyof typeof BIRD.poses;
export const BIRD_POSES = Object.keys(BIRD.poses) as BirdPose[];
