#!/usr/bin/env python3
# Copyright (c) 2026 webOS Phoenix contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate the keyboard's emoji suggestions for words
(shell/qml/Phoenix/Shell/EmojiWords.js) from CLDR's English emoji
annotations (GAPS V3, V6).

Each one-word keyword of an emoji in CLDR's annotations ("pizza", "happy",
"love"), and each one-word short name, points to the emoji that have it,
at most three: the ones named by it first ("pizza"), then those with it
in their names ("beer mug"), then in CLDR (the keyboard's) order. Only emoji the keyboard offers (EmojiData.js, generated from
emoji-test.txt 15.1) are kept, so the CLDR release must be the one for
Emoji 15.1: CLDR 44. Country flags come from the derived annotations
("france" for the French flag). Words shorter than three letters and
function words are left out: they would put an emoji in the bar for every
"the".

    tools/gen-emoji-words.py annotations.json annotationsDerived.json
    (https://github.com/unicode-org/cldr-json, tag 44.1.0:
     cldr-json/cldr-annotations-full/annotations/en/annotations.json and
     cldr-json/cldr-annotations-derived-full/annotationsDerived/en/annotations.json;
     Unicode License v3, docs/LEGAL.md)
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
EMOJI_DATA = os.path.join(HERE, "..", "shell", "qml", "Phoenix", "Shell", "EmojiData.js")
OUT = os.path.join(HERE, "..", "shell", "qml", "Phoenix", "Shell", "EmojiWords.js")
MAX_PER_WORD = 3
STOP = set("""
    and are but can for from had has have her his its not off one our out own she
    than that the their them then there these they this those too two was were
    what when who why with you your yes all any big get got may new now old see
    way use top end
""".split())
WORD = re.compile(r"^[a-z][a-z']+$")


def strip_vs(e):
    return e.replace("️", "")


def main(annotations_path, derived_path):
    with open(EMOJI_DATA, encoding="utf-8") as f:
        offered = re.findall(r'\{"e":"([^"]+)","n":"([^"]+)"', f.read())
    order = {}
    by_bare = {}
    for i, (e, _name) in enumerate(offered):
        order[e] = i
        by_bare[strip_vs(e)] = e
    with open(annotations_path, encoding="utf-8") as f:
        ann = json.load(f)["annotations"]["annotations"]
    with open(derived_path, encoding="utf-8") as f:
        derived = json.load(f)["annotationsDerived"]["annotations"]

    words = {}   # word -> {emoji: rank (0 named by it; 10+ in its name, by length; 20 a keyword)}

    def add(word, emoji, rank):
        word = word.lower().replace("’", "'")
        if len(word) < 3 or word in STOP or not WORD.match(word):
            return
        best = words.setdefault(word, {})
        best[emoji] = min(rank, best.get(emoji, rank))

    for key, a in ann.items():
        e = by_bare.get(strip_vs(key))
        if not e:
            continue
        for name in a.get("tts", []):
            if " " not in name:
                add(name, e, 0)
        named = set(w for n in a.get("tts", []) for w in n.lower().split())
        for kw in a.get("default", []):
            if " " not in kw:
                # In the name: the shorter the name, the closer ("red heart"
                # before "heart decoration" before "heart with arrow").
                add(kw, e, 10 + min(len(named), 9) if kw.lower() in named else 20)
    # Flags: "flag: France" names the flag "france".
    for key, a in derived.items():
        e = by_bare.get(strip_vs(key))
        if not e:
            continue
        for name in a.get("tts", []):
            if name.startswith("flag: ") and " " not in name[6:]:
                add(name[6:], e, 0)

    out = {}
    for word in sorted(words):
        ranked = sorted(words[word].items(), key=lambda kv: (kv[1], order[kv[0]]))
        out[word] = "".join(e + "\u0000" for e, _ in ranked[:MAX_PER_WORD]).rstrip("\u0000").split("\u0000")

    lines = [
        "// Generated by tools/gen-emoji-words.py from CLDR 44's English emoji",
        "// annotations (Unicode License v3: docs/LEGAL.md). Do not edit.",
        "// words: a word -> the emoji suggested for it, best first.",
        ".pragma library",
        "",
        "var words = {",
    ]
    for word, emoji in out.items():
        lines.append("    %s: %s," % (json.dumps(word), json.dumps(emoji, ensure_ascii=False)))
    lines.append("};")
    lines.append("")
    lines.append("// The emoji for a word (any case), or [].")
    lines.append("function forWord(word) {")
    lines.append("    var w = String(word).toLowerCase().replace(/\\u2019/g, \"'\");")
    lines.append("    return Object.prototype.hasOwnProperty.call(words, w) ? words[w] : [];")
    lines.append("}")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("%d words -> %s" % (len(out), os.path.relpath(OUT)))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
