#!/usr/bin/env python3
# Copyright (c) 2026 webOS Phoenix contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate the keyboard's word list (shell/qml/Phoenix/Shell/WordsEnUS.js)
from AOSP LatinIME's English (US) dictionary source.

LatinIME's dictionaries/en_US_wordlist.combined.gz (Apache-2.0, The Android
Open Source Project) lists about 160,000 words, each with a frequency from
0 to 255 (a log scale), flags, and "whitelist" shortcuts: typing errors
Android corrects without asking ("ill" -> "I'll", "im" -> "I'm").

Kept: the most frequent words (MAX_WORDS), without those flagged offensive,
babytalk or nonword (they are never suggested; typing them is left alone,
so they are listed as known words without a frequency), and the
whitelist shortcuts.

    curl -s 'https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/refs/heads/main/dictionaries/en_US_wordlist.combined.gz?format=TEXT' | base64 -d > en_US_wordlist.combined.gz
    tools/gen-textassist-data.py en_US_wordlist.combined.gz
"""

import gzip
import hashlib
import json
import sys

# The file this was made from (version 54, 2014-10-31); another one is
# refused until this is updated, so the output always matches its source.
SHA256 = "0f78dd455b532be169a23f233227b811fabced4b5bd7fc9c40cc05839793bcbd"
MAX_WORDS = 60000
NEVER_SUGGESTED = {"offensive", "babytalk", "nonword"}
OUT = "shell/qml/Phoenix/Shell/WordsEnUS.js"


def parse(line):
    out = {}
    for part in line.strip().split(","):
        k, _, v = part.partition("=")
        out[k] = v
    return out


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    raw = open(sys.argv[1], "rb").read()
    if hashlib.sha256(raw).hexdigest() != SHA256:
        sys.exit("not the expected en_US_wordlist.combined.gz (SHA-256 differs); update SHA256 after checking it")
    lines = gzip.decompress(raw).decode("utf-8").splitlines()

    words, known, shortcuts = [], [], []
    current = None
    for line in lines[1:]:
        if line.startswith(" word="):
            w = parse(line)
            current = w["word"]
            if w.get("flags") in NEVER_SUGGESTED or w.get("not_a_word") == "true":
                known.append(current)
            else:
                words.append((current, int(w["f"])))
        elif line.startswith("  shortcut=") and current is not None:
            s = parse(line)
            if s.get("f") == "whitelist" and s["shortcut"] != current:
                shortcuts.append((current, s["shortcut"]))

    words.sort(key=lambda wf: -wf[1])     # stable: the file's order within a frequency
    words = words[:MAX_WORDS]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Copyright (c) 2026 webOS Phoenix contributors\n")
        f.write("// SPDX-License-Identifier: Apache-2.0\n")
        f.write("//\n")
        f.write("// Generated by tools/gen-textassist-data.py from AOSP LatinIME's\n")
        f.write("// dictionaries/en_US_wordlist.combined.gz (Apache-2.0, Copyright (c) The\n")
        f.write("// Android Open Source Project; docs/LEGAL.md). Do not edit.\n")
        f.write("//\n")
        f.write("// words: \"word<TAB>frequency\" lines, most frequent first (frequency 0-255,\n")
        f.write("// a log scale); known: words never suggested but left alone when typed;\n")
        f.write("// shortcuts: \"typed<TAB>correction\" lines, corrected without asking.\n\n")
        f.write(".pragma library\n\n")
        f.write("var locale = \"en_US\";\n")
        f.write("var words = " + json.dumps("\n".join("%s\t%d" % wf for wf in words), ensure_ascii=False) + ";\n")
        f.write("var known = " + json.dumps("\n".join(known), ensure_ascii=False) + ";\n")
        f.write("var shortcuts = " + json.dumps("\n".join("%s\t%s" % s for s in shortcuts), ensure_ascii=False) + ";\n")
    print("%s: %d words, %d known, %d shortcuts" % (OUT, len(words), len(known), len(shortcuts)))


if __name__ == "__main__":
    main()
