#!/usr/bin/env python3
# Copyright (c) 2026 webOS Phoenix contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate the keyboard's emoji data (shell/qml/Phoenix/Shell/EmojiData.js)
from Unicode's emoji-test.txt.

The emoji are in CLDR order, the order the file recommends for keyboard
palettes. Only fully-qualified emoji are kept; skin-tone variants are
attached to their base emoji as its five tones (light to dark), and only
when all of a variant's people share the tone. The version must match the
colour emoji font (shell/assets/fonts/noto-color-emoji): Noto Color Emoji
2.047 covers Emoji 15.1.

    tools/gen-emoji-data.py emoji-test.txt   (https://unicode.org/Public/emoji/15.1/emoji-test.txt)
"""

import json
import re
import sys

TONES = ["light skin tone", "medium-light skin tone", "medium skin tone",
         "medium-dark skin tone", "dark skin tone"]
# The keyboard's category tabs: emoji-test.txt's groups, People & Body
# merged into Smileys & People as on most keyboards, Component left out.
CATEGORIES = [
    ("smileys", "😀", ["Smileys & Emotion", "People & Body"]),
    ("animals", "🐻", ["Animals & Nature"]),
    ("food", "🍔", ["Food & Drink"]),
    ("activities", "⚽", ["Activities"]),
    ("travel", "🚗", ["Travel & Places"]),
    ("objects", "💡", ["Objects"]),
    ("symbols", "🔣", ["Symbols"]),
    ("flags", "🏁", ["Flags"]),
]
LINE = re.compile(r"^([0-9A-F ]+?)\s*;\s*fully-qualified\s*#\s*(\S+)\s+E(\d+\.\d+)\s+(.*)$")


def main(path):
    version = None
    group = None
    by_group = {}
    by_name = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if line.startswith("# Version:"):
                version = line.split(":", 1)[1].strip()
            if line.startswith("# group:"):
                group = line.split(":", 1)[1].strip()
                continue
            m = LINE.match(line)
            if not m or group == "Component":
                continue
            emoji = "".join(chr(int(c, 16)) for c in m.group(1).split())
            name = m.group(4)
            # "waving hand: medium skin tone" is a tone of "waving hand".
            if ": " in name:
                base, rest = name.split(": ", 1)
                if rest in TONES and base in by_name:
                    entry = by_name[base]
                    entry.setdefault("t", [None] * 5)[TONES.index(rest)] = emoji
                    continue
                if any(t in rest for t in TONES):
                    continue          # mixed tones (two people): not offered
            entry = {"e": emoji, "n": name}
            by_name[name] = entry
            by_group.setdefault(group, []).append(entry)
    for entry in by_name.values():
        if "t" in entry and None in entry["t"]:
            del entry["t"]            # an incomplete set: not offered
    cats = []
    for key, icon, groups in CATEGORIES:
        items = [e for g in groups for e in by_group.get(g, [])]
        cats.append({"key": key, "icon": icon, "emoji": items})
    out = sys.stdout
    out.write("// Generated by tools/gen-emoji-data.py from Unicode's emoji-test.txt,\n")
    out.write("// version %s (Unicode License v3: docs/LEGAL.md). Do not edit.\n" % version)
    out.write("// Categories in CLDR order; e: the emoji, n: its CLDR name,\n")
    out.write("// t: its five skin tones, light to dark, when it has them.\n")
    out.write(".pragma library\n\n")
    out.write("var version = %s;\n" % json.dumps(version))
    out.write("var categories = [\n")
    for c in cats:
        out.write("    {key: %s, icon: %s, emoji: [\n" % (json.dumps(c["key"]), json.dumps(c["icon"], ensure_ascii=False)))
        for e in c["emoji"]:
            out.write("        %s,\n" % json.dumps(e, ensure_ascii=False, separators=(",", ":")))
        out.write("    ]},\n")
    out.write("];\n")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
