#!/usr/bin/env python3
# Copyright (c) 2026 webOS Phoenix contributors
# SPDX-License-Identifier: Apache-2.0
"""Write the Phoenix Assistant's character (docs/ASSISTANT-CHARACTER.md) for
its two renderers from its one source, art/assistant-bird/bird.json:

  shell/qml/Phoenix/Shell/AssistantBirdData.js   the shell's (AssistantBird.qml)
  apps/assistant/src/bird/birdData.ts            the Assistant app's (Bird.tsx)
  apps/assistant/src/bird/bird.generated.css     its flame, extras, breath and
                                                 acting keyframes (the app's CSP
                                                 allows no style made at run time)

Both get the parts' path data and colours, the pose, eye and beak tables
and the motion as they are in bird.json, plus what is worked out here once:
each part's bounding box (cubic and quadratic curves' extremes included),
the point each flame flickers about (its key "origin", a fraction of its
box, as CSS transform-box: fill-box would take it) and the flicker keys
padded to four (the shell's flicker plays exactly three steps each way);
each pose's acting checked (its loop starts and ends at rest), its keys
filled out to [at, rotation, x, y, scale x, scale y] and padded to six
("steps", for the shell's five-step loop), and each channel's pivot.

    python3 tools/gen-assistant-bird.py           write them
    python3 tools/gen-assistant-bird.py --check   fail if any is out of date (CI)
"""

import json
import math
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "art", "assistant-bird", "bird.json")
QML_OUT = os.path.join(ROOT, "shell", "qml", "Phoenix", "Shell", "AssistantBirdData.js")
TS_OUT = os.path.join(ROOT, "apps", "assistant", "src", "bird", "birdData.ts")
CSS_OUT = os.path.join(ROOT, "apps", "assistant", "src", "bird", "bird.generated.css")

HEADER = ("Copyright (c) 2026 webOS Phoenix contributors\n"
          "SPDX-License-Identifier: Apache-2.0\n\n"
          "Generated by tools/gen-assistant-bird.py from art/assistant-bird/bird.json:\n"
          "edit that and run the tool; CI checks this file is up to date.")

# Acting (motion.acting): the parts that act, the most keys a loop has, a key at rest.
ACT_CHANNELS = ("body", "head", "eyes", "lids", "wingL", "wingR", "beak", "crest", "whole", "tail", "footL", "footR")
ACT_KEYS = 6
ACT_REST = [0, 0, 0, 1, 1]
# Moves (motion.moves): the most keys a track has, the most cues, their kinds; effects' kinds.
MOVE_KEYS = 12
MOVE_CUES = 6
MOVE_KINDS = ("enter", "leave", "idle", "react")
FX_KINDS = ("swirl", "glow", "puff", "burst")
# The easings of the effects' particles (CSS's matches of Qt's curves).
OUT_CUBIC = "cubic-bezier(0.33, 1, 0.68, 1)"
OUT_QUAD = "cubic-bezier(0.5, 1, 0.89, 1)"
IN_QUAD = "cubic-bezier(0.11, 0, 0.5, 0)"

EASE_IN_OUT = "cubic-bezier(0.42, 0, 0.58, 1)"   # CSS ease-in-out; the shell uses the same curve


def fail(msg):
    sys.exit("gen-assistant-bird: " + msg)


# ---- Bounding boxes -------------------------------------------------------------------------

TOKEN = re.compile(r"[MLQCAZ]|-?\d*\.?\d+(?:e-?\d+)?", re.I)


def path_points(d):
    """Points along an absolute path (M L Q C A Z), curves sampled finely."""
    toks = TOKEN.findall(d)
    pts, i, cur, cmd = [], 0, (0.0, 0.0), None

    def num():
        nonlocal i
        v = float(toks[i])
        i += 1
        return v

    while i < len(toks):
        if re.fullmatch(r"[A-Za-z]", toks[i]):
            cmd = toks[i]
            i += 1
            if cmd in "Zz":
                continue
        if cmd != cmd.upper():
            fail("relative path commands are not supported: " + d)
        if cmd in ("M", "L"):
            cur = (num(), num())
            pts.append(cur)
        elif cmd == "Q":
            c, e = (num(), num()), (num(), num())
            for k in range(1, 65):
                t = k / 64
                pts.append(tuple((1 - t) ** 2 * cur[j] + 2 * (1 - t) * t * c[j] + t * t * e[j] for j in range(2)))
            cur = e
        elif cmd == "C":
            c1, c2, e = (num(), num()), (num(), num()), (num(), num())
            for k in range(1, 97):
                t = k / 96
                pts.append(tuple((1 - t) ** 3 * cur[j] + 3 * (1 - t) ** 2 * t * c1[j] + 3 * (1 - t) * t * t * c2[j] + t ** 3 * e[j]
                                 for j in range(2)))
            cur = e
        elif cmd == "A":
            rx, ry, _rot, _large, _sweep = num(), num(), num(), num(), num()
            e = (num(), num())
            # Only the halves of an axis-aligned ellipse between the ends of
            # its horizontal diameter are drawn here (circles, eyes, the shadow).
            if abs(cur[1] - e[1]) > 1e-6 or abs(abs(cur[0] - e[0]) - 2 * rx) > 1e-6:
                fail("only half-ellipse arcs along a horizontal diameter are supported: " + d)
            cx = (cur[0] + e[0]) / 2
            pts += [(cx - rx, cur[1]), (cx + rx, cur[1]), (cx, cur[1] - ry), (cx, cur[1] + ry)]
            cur = e
        else:
            fail("unknown path command %r in %s" % (cmd, d))
    return pts


def bbox(d):
    pts = path_points(d)
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    return [round(min(xs), 2), round(min(ys), 2), round(max(xs), 2), round(max(ys), 2)]


# ---- The model both renderers read ------------------------------------------------------------

def build(src):
    bird = json.loads(json.dumps(src))    # a copy
    parts = bird["parts"]
    for name, p in parts.items():
        if p.get("fill") and p["fill"] not in bird["colors"] or p.get("stroke") and p["stroke"] not in bird["colors"]:
            fail("part %s: colour not in colors" % name)
        if not p.get("fill") and not p.get("stroke"):
            fail("part %s: neither fill nor stroke" % name)
        p["bbox"] = bbox(p["d"])
    poses = bird["poses"]
    for name, p in poses.items():
        if p["eyes"] not in bird["eyes"]:
            fail("pose %s: no eyes %s" % (name, p["eyes"]))
        if p["beak"] not in bird["beaks"]:
            fail("pose %s: no beak %s" % (name, p["beak"]))
        for x in p["extras"]:
            if x not in bird["extras"]:
                fail("pose %s: no extra %s" % (name, x))
    for name, e in bird["eyes"].items():
        for o in e["overlays"]:
            if o not in parts or o not in bird["overlays"]:
                fail("eyes %s: overlay %s is not a part with an entry in overlays" % (name, o))
    for name, x in bird["extras"].items():
        if x["motion"] not in ("float", "twinkle", "pulse", "bob"):
            fail("extra %s: unknown motion %s" % (name, x["motion"]))
        for p in x["parts"]:
            if p not in parts:
                fail("extra %s: no part %s" % (name, p))
    motion = bird["motion"]
    for name, f in motion["flicker"].items():
        part = parts["crest" if name == "crestGust" else name]
        keys = f["keys"]
        if not 2 <= len(keys) <= 4 or keys[0][0] != 0 or keys[-1][0] != 1:
            fail("flicker %s: 2 to 4 keys from 0 to 1" % name)
        b = part["bbox"]
        f["pivot"] = [round(b[0] + (b[2] - b[0]) * f["origin"][0], 2), round(b[1] + (b[3] - b[1]) * f["origin"][1], 2)]
        # Four keys for the shell: the last repeated (its steps take no time).
        f["keys4"] = keys + [keys[-1]] * (4 - len(keys))
    acting = motion["acting"]
    acting["pivot"] = {}
    for ch, pv in acting["channels"].items():
        if ch not in ACT_CHANNELS:
            fail("acting: unknown channel %s (the renderers have %s)" % (ch, ", ".join(ACT_CHANNELS)))
        if pv is not None and pv not in bird["pivots"]:
            fail("acting: channel %s turns about %s, not in pivots" % (ch, pv))
        # The crest's channel works in the crest's own units, about its base.
        acting["pivot"][ch] = bird["pivots"][pv] if pv is not None else [0, 0]
    for name, a in acting["poses"].items():
        if name not in poses:
            fail("acting: no pose %s" % name)
        if a["period"] <= 0:
            fail("acting %s: a period above 0" % name)
        if "every" in a and not 0 < a["every"][0] <= a["every"][1]:
            fail("acting %s: every is [min, max] ms" % name)
        a["steps"] = {}
        for ch, keys in a["tracks"].items():
            if ch not in acting["channels"]:
                fail("acting %s: no channel %s" % (name, ch))
            if not 2 <= len(keys) <= ACT_KEYS or keys[0][0] != 0 or keys[-1][0] != 1:
                fail("acting %s %s: 2 to %d keys from 0 to 1" % (name, ch, ACT_KEYS))
            full = []
            for k in keys:
                if not 1 <= len(k) <= 6:
                    fail("acting %s %s: a key is [at, rotation, x, y, scale x, scale y]" % (name, ch))
                full.append(list(k) + ACT_REST[len(k) - 1:])
            if any(full[i + 1][0] < full[i][0] for i in range(len(full) - 1)):
                fail("acting %s %s: keys out of order" % (name, ch))
            if full[0][1:] != ACT_REST or full[-1][1:] != ACT_REST:
                fail("acting %s %s: the first and last keys at rest, so the loop joins up" % (name, ch))
            # Padded to ACT_KEYS for the shell (its loop plays exactly that many steps).
            a["steps"][ch] = full + [full[-1]] * (ACT_KEYS - len(full))
    build_moves(bird)
    if len(motion["speech"]) != 8 or len(motion["listen"]) != 6:
        fail("motion.speech needs 8 steps and motion.listen 6 (AssistantBird.qml plays that many)")
    return bird


def build_moves(bird):
    """Checks the moves, effects, idles and reactions; fills each move's keys
    out to MOVE_KEYS of [at, rotation, x, y, scale x, scale y] ("steps") with
    the curve into each ("curves", the Bezier points), and its cues."""
    motion = bird["motion"]
    curves = motion["curves"]
    curves.pop("about", None)
    for name, c in curves.items():
        if len(c) != 4:
            fail("curve %s: four numbers" % name)
    effects = bird["effects"]
    effects.pop("about", None)
    for name, e in effects.items():
        if e["kind"] not in FX_KINDS:
            fail("effect %s: unknown kind %s" % (name, e["kind"]))
        if e["period"] <= 0:
            fail("effect %s: a period above 0" % name)
        if e["kind"] == "glow":
            keys = e["keys"]
            if not 2 <= len(keys) <= 4 or keys[0][0] != 0 or keys[-1][0] != 1:
                fail("effect %s: 2 to 4 keys from 0 to 1" % name)
            full = [list(k[:3]) + [k[3] if len(k) > 3 else "io"] for k in keys]
            for k in full:
                if k[3] not in curves:
                    fail("effect %s: no curve %s" % (name, k[3]))
            # Four for the shell (three steps), the last repeated.
            e["keys4"] = [k[:3] + [curves[k[3]]] for k in full] + [full[-1][:3] + [curves["lin"]]] * (4 - len(full))
        else:
            for p in e["particles"]:
                if p[3] >= e["period"]:
                    fail("effect %s: a particle's delay within the period" % name)
                if len(p) > 4 and p[4] not in bird["colors"]:
                    fail("effect %s: colour %s not in colors" % (name, p[4]))
    moves = motion["moves"]
    moves.pop("about", None)
    channels = motion["acting"]["channels"]
    for name, m in moves.items():
        if m["kind"] not in MOVE_KINDS:
            fail("move %s: unknown kind %s" % (name, m["kind"]))
        if m["period"] <= 0:
            fail("move %s: a period above 0" % name)
        m["steps"], m["curves"] = {}, {}
        for ch, keys in m["tracks"].items():
            if ch not in channels:
                fail("move %s: no channel %s" % (name, ch))
            if not 2 <= len(keys) <= MOVE_KEYS or keys[0][0] != 0 or keys[-1][0] != 1:
                fail("move %s %s: 2 to %d keys from 0 to 1" % (name, ch, MOVE_KEYS))
            full, into = [], []
            for k in keys:
                k = list(k)
                curve = k.pop() if isinstance(k[-1], str) else "io"
                if curve not in curves:
                    fail("move %s %s: no curve %s" % (name, ch, curve))
                if not 1 <= len(k) <= 6:
                    fail("move %s %s: a key is [at, rotation, x, y, scale x, scale y, curve]" % (name, ch))
                full.append(k + ACT_REST[len(k) - 1:])
                into.append(curve)
            if any(full[i + 1][0] < full[i][0] for i in range(len(full) - 1)):
                fail("move %s %s: keys out of order" % (name, ch))
            if m["kind"] != "enter" and full[0][1:] != ACT_REST:
                fail("move %s %s: the first key at rest (only an enter starts away)" % (name, ch))
            if m["kind"] != "leave" and full[-1][1:] != ACT_REST:
                fail("move %s %s: the last key at rest (only a leave holds)" % (name, ch))
            m["steps"][ch] = full + [full[-1]] * (MOVE_KEYS - len(full))
            m["curves"][ch] = [curves[c] for c in into[1:]] + [curves["lin"]] * (MOVE_KEYS - len(full))
        cues = m.setdefault("cues", [])
        if len(cues) > MOVE_CUES:
            fail("move %s: at most %d cues" % (name, MOVE_CUES))
        if any(cues[i + 1]["at"] < cues[i]["at"] for i in range(len(cues) - 1)):
            fail("move %s: cues out of order" % name)
        for c in cues:
            if not 0 <= c["at"] <= 1:
                fail("move %s: a cue's at is 0 to 1" % name)
            if c.get("eyes") and c["eyes"] not in bird["eyes"]:
                fail("move %s: no eyes %s" % (name, c["eyes"]))
            if c.get("beak") and c["beak"] not in bird["beaks"]:
                fail("move %s: no beak %s" % (name, c["beak"]))
            if "fx" in c and c["fx"] not in effects:
                fail("move %s: no effect %s" % (name, c["fx"]))
    for name in motion["idles"]["pool"]:
        if moves.get(name, {}).get("kind") != "idle":
            fail("idles: %s is no idle move" % name)
    r = motion["reactions"]
    for key in ("type", "erase", "pause", "send", "tap", "move"):
        for name in (r[key] if isinstance(r[key], list) else [r[key]]):
            if moves.get(name, {}).get("kind") != "react":
                fail("reactions %s: %s is no react move" % (key, name))
    for kind in ("enter", "leave"):
        if moves.get(kind, {}).get("kind") != kind:
            fail("moves: an %s of kind %s is needed" % (kind, kind))


# ---- Writers -----------------------------------------------------------------------------------

def dumps(o):
    return json.dumps(o, indent=1, ensure_ascii=False)


def qml_js(bird):
    head = "\n".join("// " + l if l else "//" for l in HEADER.split("\n"))
    return "%s\n\n.pragma library\n\nvar bird = %s;\n" % (head, dumps(bird))


def ts(bird):
    head = "\n".join("// " + l if l else "//" for l in HEADER.split("\n"))
    return ("%s\n\n/* eslint-disable */\nexport const BIRD = %s as const;\n\n"
            "export type BirdPose = keyof typeof BIRD.poses;\n"
            "export const BIRD_POSES = Object.keys(BIRD.poses) as BirdPose[];\n") % (head, dumps(bird))


def num(v):
    s = ("%.4f" % v).rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def css(bird):
    out = ["/* " + "\n".join(" * " + l if l else " *" for l in HEADER.split("\n")).lstrip(" *").lstrip() + "\n *",
           " * The duration of each is multiplied by --ab-speed (the app's animation",
           " * speed); prefers-reduced-motion stops them (Bird.tsx holds still too). */", ""]
    for name, f in bird["motion"]["flicker"].items():
        px, py = f["pivot"]
        out.append("@keyframes ab-%s {" % name)
        for at, sx, sy, rot, o in f["keys"]:
            out.append("    %s%% { transform: translate(%spx, %spx) rotate(%sdeg) scale(%s, %s) translate(%spx, %spx); opacity: %s; }"
                       % (num(at * 100), num(px), num(py), num(rot), num(sx), num(sy), num(-px), num(-py), num(o)))
        out.append("}")
        out.append(".ab-flicker-%s { animation: ab-%s calc(%dms * var(--ab-speed, 1)) %s infinite alternate; }"
                   % (name, name, f["period"], EASE_IN_OUT))
        out.append("")
    for name, x in bird["extras"].items():
        n = len(x["parts"])
        out.append("@keyframes ab-%s {" % name)
        if x["motion"] == "float":
            out.append("    0% { transform: translate(0px, 0px); opacity: 0; }")
            out.append("    25% { opacity: 1; }")
            out.append("    70% { opacity: 1; }")
            out.append("    100%% { transform: translate(0px, %spx); opacity: 0; }" % num(x["dy"]))
            timing, direction = "linear", "normal"
        elif x["motion"] == "bob":
            out.append("    0% { transform: translate(0px, 0px); }")
            out.append("    100%% { transform: translate(0px, %spx); }" % num(x["dy"]))
            timing, direction = EASE_IN_OUT, "alternate"
        elif x["motion"] == "pulse":
            out.append("    0% { opacity: 1; }")
            out.append("    100%% { opacity: %s; }" % num(x["low"]))
            timing, direction = EASE_IN_OUT, "alternate"
        else:   # twinkle: about each part's own centre (its own keyframes below)
            out.pop()
            for i, p in enumerate(x["parts"]):
                b = bird["parts"][p]["bbox"]
                cx, cy = (b[0] + b[2]) / 2, (b[1] + b[3]) / 2
                out.append("@keyframes ab-%s-%d {" % (name, i + 1))
                out.append("    0%% { transform: translate(%spx, %spx) scale(1) translate(%spx, %spx); }" % (num(cx), num(cy), num(-cx), num(-cy)))
                out.append("    100%% { transform: translate(%spx, %spx) scale(%s) translate(%spx, %spx); }"
                           % (num(cx), num(cy), num(x["scale"]), num(-cx), num(-cy)))
                out.append("}")
            for i in range(n):
                out.append(".ab-%s-%d { animation: ab-%s-%d calc(%dms * var(--ab-speed, 1)) %s calc(%dms * var(--ab-speed, 1)) infinite alternate; }"
                           % (name, i + 1, name, i + 1, x["period"], EASE_IN_OUT, x["stagger"] * i))
            out.append("")
            continue
        out.append("}")
        for i in range(n):
            out.append(".ab-%s-%d { animation: ab-%s calc(%dms * var(--ab-speed, 1)) %s calc(%dms * var(--ab-speed, 1)) infinite %s; }"
                       % (name, i + 1, name, x["period"], timing, x["stagger"] * i, direction))
        out.append("")
    b = bird["motion"]["breath"]
    px, py = bird["pivots"]["breath"]
    out.append("@keyframes ab-breath {")
    out.append("    0%% { transform: translate(%spx, %spx) scale(1, 1) translate(%spx, %spx); }" % (num(px), num(py), num(-px), num(-py)))
    out.append("    100%% { transform: translate(%spx, %spx) scale(%s, %s) translate(%spx, %spx); }"
               % (num(px), num(py), num(b["scaleX"]), num(b["scaleY"]), num(-px), num(-py)))
    out.append("}")
    out.append(".ab-breath { animation: ab-breath calc(%dms * var(--ab-speed, 1)) %s infinite alternate; }" % (b["period"] // 2, EASE_IN_OUT))
    out.append("")
    # The hop: take-off (down on its feet, up stretched) and landing
    # (falling stretched, a squash, springing back), about its feet.
    h = bird["motion"]["hop"]
    fx, fy = bird["pivots"]["feet"]

    def squash(pct, sx, sy):
        return "    %s%% { transform: translate(%spx, %spx) scale(%s, %s) translate(%spx, %spx); }" % (
            num(pct), num(fx), num(fy), num(sx), num(sy), num(-fx), num(-fy))
    up = h["takeoff"] + h["rise"]
    out.append("@keyframes ab-takeoff {")
    out.append(squash(0, 1, 1))
    out.append(squash(100 * h["takeoff"] / up, *h["squash"]))
    out.append(squash(100 * (h["takeoff"] + 0.4 * h["rise"]) / up, *h["stretch"]))
    out.append(squash(100, 1, 1))
    out.append("}")
    out.append(".ab-takeoff { animation: ab-takeoff calc(%dms * var(--ab-speed, 1)) ease-out; }" % up)
    down = h["fall"] + h["land"] + h["settle"]
    out.append("@keyframes ab-landing {")
    out.append(squash(0, 1, 1))
    out.append(squash(100 * h["fall"] / down, *h["stretch"]))
    out.append(squash(100 * (h["fall"] + h["land"]) / down, *h["squash"]))
    out.append(squash(100, 1, 1))
    out.append("}")
    out.append(".ab-landing { animation: ab-landing calc(%dms * var(--ab-speed, 1)) ease-in-out; }" % down)
    out.append("")
    # Speaking: the beak in the syllable rhythm (motion.speech), the lower
    # jaw and the mouth from the jaw's top, the upper beak from its edge.
    steps = bird["motion"]["speech"]
    total = sum(ms for _o, ms in steps)
    jx, jy = bird["pivots"]["jaw"]
    ux, uy = bird["pivots"]["upperBeak"]
    usy = bird["beaks"][bird["poses"]["speaking"]["beak"]]["upper"][1]
    for name, (px, py), f in (("jaw", (jx, jy), lambda o: 0.62 + 0.38 * o), ("mouth", (jx, jy), lambda o: o),
                              ("upper", (ux, uy), lambda o: usy + (1 - usy) * (1 - o))):
        out.append("@keyframes ab-talk-%s {" % name)
        t = 0
        out.append("    0%% { transform: translate(%spx, %spx) scale(1, %s) translate(%spx, %spx); }"
                   % (num(px), num(py), num(f(steps[-1][0])), num(-px), num(-py)))
        for o, ms in steps:
            t += ms
            out.append("    %s%% { transform: translate(%spx, %spx) scale(1, %s) translate(%spx, %spx); }"
                       % (num(100 * t / total), num(px), num(py), num(f(o)), num(-px), num(-py)))
        out.append("}")
        out.append(".ab-talk-%s { animation: ab-talk-%s calc(%dms * var(--ab-speed, 1)) ease-in-out infinite; }" % (name, name, total))
    out.append("")
    # Acting: each pose's loops, one per part that acts, about the part's pivot.
    acting = bird["motion"]["acting"]
    for pose, a in acting["poses"].items():
        for ch, keys in a["tracks"].items():
            px, py = acting["pivot"][ch]
            out.append("@keyframes ab-act-%s-%s {" % (pose, ch))
            for at, rot, tx, ty, sx, sy in a["steps"][ch][:len(keys)]:
                out.append("    %s%% { transform: translate(%spx, %spx) translate(%spx, %spx) rotate(%sdeg) scale(%s, %s) translate(%spx, %spx); }"
                           % (num(at * 100), num(tx), num(ty), num(px), num(py), num(rot), num(sx), num(sy), num(-px), num(-py)))
            out.append("}")
            out.append(".ab-act-%s-%s { animation: ab-act-%s-%s calc(%dms * var(--ab-speed, 1)) %s %s; }"
                       % (pose, ch, pose, ch, a["period"], EASE_IN_OUT, "1" if "every" in a else "infinite"))
        out.append("")
    out += css_moves(bird)
    out += css_effects(bird)
    out.append("@media (prefers-reduced-motion: reduce) {")
    out.append("    .ab-bird * { animation: none !important; transition: none !important; }")
    out.append("}")
    out.append(".ab-bird.ab-still * { animation: none !important; transition: none !important; }")
    return "\n".join(out) + "\n"


def bezier(c):
    return "cubic-bezier(%s)" % ", ".join(num(v) for v in c)


def css_moves(bird):
    """Each move's keyframes per channel, about the channel's pivot, each
    key's curve on the way into it (CSS takes a keyframe's timing function
    for the way out of it). Filled both ways: an enter is hidden through its
    delay (--ab-delay), a leave holds its end."""
    out = []
    acting = bird["motion"]["acting"]
    for name, m in bird["motion"]["moves"].items():
        for ch, keys in m["tracks"].items():
            px, py = acting["pivot"][ch]
            n = len(keys)
            steps, curves = m["steps"][ch][:n], m["curves"][ch]
            out.append("@keyframes ab-mv-%s-%s {" % (name, ch))
            for i, (at, rot, tx, ty, sx, sy) in enumerate(steps):
                timing = "; animation-timing-function: %s" % bezier(curves[i]) if i < n - 1 else ""
                out.append("    %s%% { transform: translate(%spx, %spx) translate(%spx, %spx) rotate(%sdeg) scale(%s, %s) translate(%spx, %spx)%s; }"
                           % (num(at * 100), num(tx), num(ty), num(px), num(py), num(rot), num(sx), num(sy), num(-px), num(-py), timing))
            out.append("}")
            out.append(".ab-mv-%s-%s { animation: ab-mv-%s-%s calc(%dms * var(--ab-speed, 1)) linear calc(var(--ab-delay, 0ms) * var(--ab-speed, 1)) both; }"
                       % (name, ch, name, ch, m["period"]))
        out.append("")
    return out


def css_effects(bird):
    """The effects' particles: each a few nested groups (where it goes, how
    big, how bright), each with its own curve, as the shell plays them."""
    out = []

    def anim(cls, ms, timing, delay=0):
        return ".%s { animation: %s calc(%dms * var(--ab-speed, 1)) %s calc(%dms * var(--ab-speed, 1)) both; }" % (
            cls, cls, ms, timing, delay)
    for name, e in bird["effects"].items():
        ox, oy = e["origin"]
        if e["kind"] == "glow":
            cls = "ab-fx-%s" % name
            out.append("@keyframes %s {" % cls)
            keys = e["keys"]
            for i, k in enumerate(keys):
                at, sc, op = k[:3]
                nxt = keys[i + 1] if i + 1 < len(keys) else None
                timing = "; animation-timing-function: %s" % bezier(bird["motion"]["curves"][nxt[3] if len(nxt) > 3 else "io"]) if nxt else ""
                out.append("    %s%% { transform: translate(%spx, %spx) scale(%s); opacity: %s%s; }" % (num(at * 100), num(ox), num(oy), num(sc), num(op), timing))
            out.append("}")
            out.append(anim(cls, e["period"], "linear"))
            out.append("")
            continue
        for i, p in enumerate(e["particles"]):
            cls = "ab-fx-%s-%d" % (name, i + 1)
            delay = p[3]
            ms = e["period"] - delay
            if e["kind"] == "swirl":
                a, r = p[0], p[1]
                out.append("@keyframes %s-a { 0%% { transform: translate(%spx, %spx) rotate(%sdeg); } 100%% { transform: translate(%spx, %spx) rotate(%sdeg); } }"
                           % (cls, num(ox), num(oy), num(a), num(ox), num(oy), num(a + e["spin"])))
                out.append("@keyframes %s-r { 0%% { transform: translate(%spx, 0px) scale(1); } 100%% { transform: translate(0px, 0px) scale(0.4); } }" % (cls, num(r)))
                out.append("@keyframes %s-o { 0%% { opacity: 0; } 25%% { opacity: 1; } 100%% { opacity: 1; } }" % cls)
                out.append(anim(cls + "-a", ms, IN_QUAD, delay))
                out.append(anim(cls + "-r", ms, IN_QUAD, delay))
                out.append(anim(cls + "-o", ms, "linear", delay))
            elif e["kind"] == "puff":
                dx, dy = p[0], p[1]
                out.append("@keyframes %s-t { 0%% { transform: translate(%spx, %spx); } 100%% { transform: translate(%spx, %spx); } }"
                           % (cls, num(ox), num(oy), num(ox + dx), num(oy + dy)))
                out.append("@keyframes %s-s { 0%% { transform: scale(0.35); } 100%% { transform: scale(1); } }" % cls)
                out.append("@keyframes %s-o { 0%% { opacity: 0; animation-timing-function: %s; } 15%% { opacity: 0.85; } 40%% { opacity: 0.85; animation-timing-function: %s; } 100%% { opacity: 0; } }"
                           % (cls, OUT_QUAD, IN_QUAD))
                out.append(anim(cls + "-t", ms, OUT_CUBIC, delay))
                out.append(anim(cls + "-s", ms, OUT_QUAD, delay))
                out.append(anim(cls + "-o", ms, "linear", delay))
            else:   # burst
                dx, dy = p[0], p[1]
                out.append("@keyframes %s-t { 0%% { transform: translate(%spx, %spx); } 100%% { transform: translate(%spx, %spx); } }"
                           % (cls, num(ox), num(oy), num(ox + dx), num(oy + dy)))
                out.append("@keyframes %s-s { 0%% { transform: scale(1); } 100%% { transform: scale(0.3); } }" % cls)
                out.append("@keyframes %s-o { 0%% { opacity: 1; } 100%% { opacity: 0; } }" % cls)
                out.append(anim(cls + "-t", ms, OUT_CUBIC, delay))
                out.append(anim(cls + "-s", ms, "linear", delay))
                out.append(anim(cls + "-o", ms, IN_QUAD, delay))
        out.append("")
    return out


def main():
    check = "--check" in sys.argv[1:]
    with open(SOURCE, encoding="utf-8") as f:
        bird = build(json.load(f))
    outputs = {QML_OUT: qml_js(bird), TS_OUT: ts(bird), CSS_OUT: css(bird)}
    stale = []
    for path, text in outputs.items():
        try:
            with open(path, encoding="utf-8") as f:
                same = f.read() == text
        except FileNotFoundError:
            same = False
        if same:
            continue
        if check:
            stale.append(os.path.relpath(path, ROOT))
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
            print("wrote " + os.path.relpath(path, ROOT))
    if stale:
        fail("out of date (run tools/gen-assistant-bird.py): " + ", ".join(stale))


if __name__ == "__main__":
    main()
