#!/usr/bin/env python3
# Copyright (c) 2026 webOS Phoenix contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate the keyboard's word lists (shell/qml/Phoenix/Shell/Words*.js)
from AOSP LatinIME's dictionary sources: English (US), German and French,
the languages of the keyboard's QWERTY, QWERTZ and AZERTY layouts.

LatinIME's dictionaries/<locale>_wordlist.combined.gz (Apache-2.0, The
Android Open Source Project) lists about 160,000 words, each with a frequency from
0 to 255 (a log scale), flags, and "whitelist" shortcuts: typing errors
Android corrects without asking ("ill" -> "I'll", "im" -> "I'm").

Kept: the most frequent words (MAX_WORDS), without those flagged offensive,
babytalk or nonword (they are never suggested; typing them is left alone,
so they are listed as known words without a frequency), and the
whitelist shortcuts.

    for l in en_US de fr; do
        curl -s "https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/refs/heads/main/dictionaries/${l}_wordlist.combined.gz?format=TEXT" | base64 -d > ${l}_wordlist.combined.gz
        tools/gen-textassist-data.py ${l}_wordlist.combined.gz
    done
"""

import gzip
import hashlib
import json
import sys

# The files these were made from (version 54, 2014-10-31), by locale: the
# SHA-256 and the output. Another file is refused until this is updated, so
# the output always matches its source.
SOURCES = {
    "en_US": ("0f78dd455b532be169a23f233227b811fabced4b5bd7fc9c40cc05839793bcbd", "shell/qml/Phoenix/Shell/WordsEnUS.js"),
    "de": ("07ae553cd55f9901412065bad7617379908ed5f2a701d226ffde85a9b8ffd5c0", "shell/qml/Phoenix/Shell/WordsDe.js"),
    "fr": ("cc917a0a81acab0ea12089c2fb06b5c6be98c75f23a7605bfdbbeb698abfd65e", "shell/qml/Phoenix/Shell/WordsFr.js"),
}
MAX_WORDS = 60000
NEVER_SUGGESTED = {"offensive", "babytalk", "nonword"}


def parse(line):
    out = {}
    for part in line.strip().split(","):
        k, _, v = part.partition("=")
        out[k] = v
    return out


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    raw = open(sys.argv[1], "rb").read()
    digest = hashlib.sha256(raw).hexdigest()
    found = [(loc, out) for loc, (sha, out) in SOURCES.items() if sha == digest]
    if not found:
        sys.exit("not one of the expected <locale>_wordlist.combined.gz files (SHA-256 differs); update SOURCES after checking it")
    locale, OUT = found[0]
    lines = gzip.decompress(raw).decode("utf-8").splitlines()

    words, known, shortcuts = [], [], []
    current = None
    for line in lines[1:]:
        if line.startswith(" word="):
            w = parse(line)
            current = w["word"]
            if w.get("flags") in NEVER_SUGGESTED or w.get("not_a_word") == "true":
                known.append(current)
            else:
                words.append((current, int(w["f"])))
        elif line.startswith("  shortcut=") and current is not None:
            s = parse(line)
            if s.get("f") == "whitelist" and s["shortcut"] != current:
                shortcuts.append((current, s["shortcut"]))

    words.sort(key=lambda wf: -wf[1])     # stable: the file's order within a frequency
    words = words[:MAX_WORDS]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Copyright (c) 2026 webOS Phoenix contributors\n")
        f.write("// SPDX-License-Identifier: Apache-2.0\n")
        f.write("//\n")
        f.write("// Generated by tools/gen-textassist-data.py from AOSP LatinIME's\n")
        f.write("// dictionaries/%s_wordlist.combined.gz (Apache-2.0, Copyright (c) The\n" % locale)
        f.write("// Android Open Source Project; docs/LEGAL.md). Do not edit.\n")
        f.write("//\n")
        f.write("// words: \"word<TAB>frequency\" lines, most frequent first (frequency 0-255,\n")
        f.write("// a log scale); known: words never suggested but left alone when typed;\n")
        f.write("// shortcuts: \"typed<TAB>correction\" lines, corrected without asking.\n\n")
        f.write(".pragma library\n\n")
        f.write("var locale = \"%s\";\n" % locale)
        f.write("var words = " + json.dumps("\n".join("%s\t%d" % wf for wf in words), ensure_ascii=False) + ";\n")
        f.write("var known = " + json.dumps("\n".join(known), ensure_ascii=False) + ";\n")
        f.write("var shortcuts = " + json.dumps("\n".join("%s\t%s" % s for s in shortcuts), ensure_ascii=False) + ";\n")
    print("%s: %d words, %d known, %d shortcuts" % (OUT, len(words), len(known), len(shortcuts)))


if __name__ == "__main__":
    main()
