#!/usr/bin/env python3
# Copyright (c) 2026 webOS Phoenix contributors
# SPDX-License-Identifier: Apache-2.0
"""Write the Phoenix Assistant's character (docs/ASSISTANT-CHARACTER.md) for
its two renderers from its one source, art/assistant-bird/bird.json:

  shell/qml/Phoenix/Shell/AssistantBirdData.js   the shell's (AssistantBird.qml)
  apps/assistant/src/bird/birdData.ts            the Assistant app's (Bird.tsx)
  apps/assistant/src/bird/bird.generated.css     its flame, extras and breath
                                                 keyframes (the app's CSP allows
                                                 no style made at run time)

Both get the parts' path data and colours, the pose, eye and beak tables
and the motion as they are in bird.json, plus what is worked out here once:
each part's bounding box (cubic and quadratic curves' extremes included),
the point each flame flickers about (its key "origin", a fraction of its
box, as CSS transform-box: fill-box would take it) and the flicker keys
padded to four (the shell's flicker plays exactly three steps each way).

    python3 tools/gen-assistant-bird.py           write them
    python3 tools/gen-assistant-bird.py --check   fail if any is out of date (CI)
"""

import json
import math
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "art", "assistant-bird", "bird.json")
QML_OUT = os.path.join(ROOT, "shell", "qml", "Phoenix", "Shell", "AssistantBirdData.js")
TS_OUT = os.path.join(ROOT, "apps", "assistant", "src", "bird", "birdData.ts")
CSS_OUT = os.path.join(ROOT, "apps", "assistant", "src", "bird", "bird.generated.css")

HEADER = ("Copyright (c) 2026 webOS Phoenix contributors\n"
          "SPDX-License-Identifier: Apache-2.0\n\n"
          "Generated by tools/gen-assistant-bird.py from art/assistant-bird/bird.json:\n"
          "edit that and run the tool; CI checks this file is up to date.")

EASE_IN_OUT = "cubic-bezier(0.42, 0, 0.58, 1)"   # CSS ease-in-out; the shell uses the same curve


def fail(msg):
    sys.exit("gen-assistant-bird: " + msg)


# ---- Bounding boxes -------------------------------------------------------------------------

TOKEN = re.compile(r"[MLQCAZ]|-?\d*\.?\d+(?:e-?\d+)?", re.I)


def path_points(d):
    """Points along an absolute path (M L Q C A Z), curves sampled finely."""
    toks = TOKEN.findall(d)
    pts, i, cur, cmd = [], 0, (0.0, 0.0), None

    def num():
        nonlocal i
        v = float(toks[i])
        i += 1
        return v

    while i < len(toks):
        if re.fullmatch(r"[A-Za-z]", toks[i]):
            cmd = toks[i]
            i += 1
            if cmd in "Zz":
                continue
        if cmd != cmd.upper():
            fail("relative path commands are not supported: " + d)
        if cmd in ("M", "L"):
            cur = (num(), num())
            pts.append(cur)
        elif cmd == "Q":
            c, e = (num(), num()), (num(), num())
            for k in range(1, 65):
                t = k / 64
                pts.append(tuple((1 - t) ** 2 * cur[j] + 2 * (1 - t) * t * c[j] + t * t * e[j] for j in range(2)))
            cur = e
        elif cmd == "C":
            c1, c2, e = (num(), num()), (num(), num()), (num(), num())
            for k in range(1, 97):
                t = k / 96
                pts.append(tuple((1 - t) ** 3 * cur[j] + 3 * (1 - t) ** 2 * t * c1[j] + 3 * (1 - t) * t * t * c2[j] + t ** 3 * e[j]
                                 for j in range(2)))
            cur = e
        elif cmd == "A":
            rx, ry, _rot, _large, _sweep = num(), num(), num(), num(), num()
            e = (num(), num())
            # Only the halves of an axis-aligned ellipse between the ends of
            # its horizontal diameter are drawn here (circles, eyes, the shadow).
            if abs(cur[1] - e[1]) > 1e-6 or abs(abs(cur[0] - e[0]) - 2 * rx) > 1e-6:
                fail("only half-ellipse arcs along a horizontal diameter are supported: " + d)
            cx = (cur[0] + e[0]) / 2
            pts += [(cx - rx, cur[1]), (cx + rx, cur[1]), (cx, cur[1] - ry), (cx, cur[1] + ry)]
            cur = e
        else:
            fail("unknown path command %r in %s" % (cmd, d))
    return pts


def bbox(d):
    pts = path_points(d)
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    return [round(min(xs), 2), round(min(ys), 2), round(max(xs), 2), round(max(ys), 2)]


# ---- The model both renderers read ------------------------------------------------------------

def build(src):
    bird = json.loads(json.dumps(src))    # a copy
    parts = bird["parts"]
    for name, p in parts.items():
        if p.get("fill") and p["fill"] not in bird["colors"] or p.get("stroke") and p["stroke"] not in bird["colors"]:
            fail("part %s: colour not in colors" % name)
        if not p.get("fill") and not p.get("stroke"):
            fail("part %s: neither fill nor stroke" % name)
        p["bbox"] = bbox(p["d"])
    poses = bird["poses"]
    for name, p in poses.items():
        if p["eyes"] not in bird["eyes"]:
            fail("pose %s: no eyes %s" % (name, p["eyes"]))
        if p["beak"] not in bird["beaks"]:
            fail("pose %s: no beak %s" % (name, p["beak"]))
        for x in p["extras"]:
            if x not in bird["extras"]:
                fail("pose %s: no extra %s" % (name, x))
    for name, e in bird["eyes"].items():
        for o in e["overlays"]:
            if o not in parts or o not in bird["overlays"]:
                fail("eyes %s: overlay %s is not a part with an entry in overlays" % (name, o))
    for name, x in bird["extras"].items():
        if x["motion"] not in ("float", "twinkle", "pulse", "bob"):
            fail("extra %s: unknown motion %s" % (name, x["motion"]))
        for p in x["parts"]:
            if p not in parts:
                fail("extra %s: no part %s" % (name, p))
    motion = bird["motion"]
    for name, f in motion["flicker"].items():
        part = parts["crest" if name == "crestGust" else name]
        keys = f["keys"]
        if not 2 <= len(keys) <= 4 or keys[0][0] != 0 or keys[-1][0] != 1:
            fail("flicker %s: 2 to 4 keys from 0 to 1" % name)
        b = part["bbox"]
        f["pivot"] = [round(b[0] + (b[2] - b[0]) * f["origin"][0], 2), round(b[1] + (b[3] - b[1]) * f["origin"][1], 2)]
        # Four keys for the shell: the last repeated (its steps take no time).
        f["keys4"] = keys + [keys[-1]] * (4 - len(keys))
    if len(motion["speech"]) != 8 or len(motion["listen"]) != 6:
        fail("motion.speech needs 8 steps and motion.listen 6 (AssistantBird.qml plays that many)")
    return bird


# ---- Writers -----------------------------------------------------------------------------------

def dumps(o):
    return json.dumps(o, indent=1, ensure_ascii=False)


def qml_js(bird):
    head = "\n".join("// " + l if l else "//" for l in HEADER.split("\n"))
    return "%s\n\n.pragma library\n\nvar bird = %s;\n" % (head, dumps(bird))


def ts(bird):
    head = "\n".join("// " + l if l else "//" for l in HEADER.split("\n"))
    return ("%s\n\n/* eslint-disable */\nexport const BIRD = %s as const;\n\n"
            "export type BirdPose = keyof typeof BIRD.poses;\n"
            "export const BIRD_POSES = Object.keys(BIRD.poses) as BirdPose[];\n") % (head, dumps(bird))


def num(v):
    s = ("%.4f" % v).rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def css(bird):
    out = ["/* " + "\n".join(" * " + l if l else " *" for l in HEADER.split("\n")).lstrip(" *").lstrip() + "\n *",
           " * The duration of each is multiplied by --ab-speed (the app's animation",
           " * speed); prefers-reduced-motion stops them (Bird.tsx holds still too). */", ""]
    for name, f in bird["motion"]["flicker"].items():
        px, py = f["pivot"]
        out.append("@keyframes ab-%s {" % name)
        for at, sx, sy, rot, o in f["keys"]:
            out.append("    %s%% { transform: translate(%spx, %spx) rotate(%sdeg) scale(%s, %s) translate(%spx, %spx); opacity: %s; }"
                       % (num(at * 100), num(px), num(py), num(rot), num(sx), num(sy), num(-px), num(-py), num(o)))
        out.append("}")
        out.append(".ab-flicker-%s { animation: ab-%s calc(%dms * var(--ab-speed, 1)) %s infinite alternate; }"
                   % (name, name, f["period"], EASE_IN_OUT))
        out.append("")
    for name, x in bird["extras"].items():
        n = len(x["parts"])
        out.append("@keyframes ab-%s {" % name)
        if x["motion"] == "float":
            out.append("    0% { transform: translate(0px, 0px); opacity: 0; }")
            out.append("    25% { opacity: 1; }")
            out.append("    70% { opacity: 1; }")
            out.append("    100%% { transform: translate(0px, %spx); opacity: 0; }" % num(x["dy"]))
            timing, direction = "linear", "normal"
        elif x["motion"] == "bob":
            out.append("    0% { transform: translate(0px, 0px); }")
            out.append("    100%% { transform: translate(0px, %spx); }" % num(x["dy"]))
            timing, direction = EASE_IN_OUT, "alternate"
        elif x["motion"] == "pulse":
            out.append("    0% { opacity: 1; }")
            out.append("    100%% { opacity: %s; }" % num(x["low"]))
            timing, direction = EASE_IN_OUT, "alternate"
        else:   # twinkle: about each part's own centre (its own keyframes below)
            out.pop()
            for i, p in enumerate(x["parts"]):
                b = bird["parts"][p]["bbox"]
                cx, cy = (b[0] + b[2]) / 2, (b[1] + b[3]) / 2
                out.append("@keyframes ab-%s-%d {" % (name, i + 1))
                out.append("    0%% { transform: translate(%spx, %spx) scale(1) translate(%spx, %spx); }" % (num(cx), num(cy), num(-cx), num(-cy)))
                out.append("    100%% { transform: translate(%spx, %spx) scale(%s) translate(%spx, %spx); }"
                           % (num(cx), num(cy), num(x["scale"]), num(-cx), num(-cy)))
                out.append("}")
            for i in range(n):
                out.append(".ab-%s-%d { animation: ab-%s-%d calc(%dms * var(--ab-speed, 1)) %s calc(%dms * var(--ab-speed, 1)) infinite alternate; }"
                           % (name, i + 1, name, i + 1, x["period"], EASE_IN_OUT, x["stagger"] * i))
            out.append("")
            continue
        out.append("}")
        for i in range(n):
            out.append(".ab-%s-%d { animation: ab-%s calc(%dms * var(--ab-speed, 1)) %s calc(%dms * var(--ab-speed, 1)) infinite %s; }"
                       % (name, i + 1, name, x["period"], timing, x["stagger"] * i, direction))
        out.append("")
    b = bird["motion"]["breath"]
    px, py = bird["pivots"]["breath"]
    out.append("@keyframes ab-breath {")
    out.append("    0%% { transform: translate(%spx, %spx) scale(1, 1) translate(%spx, %spx); }" % (num(px), num(py), num(-px), num(-py)))
    out.append("    100%% { transform: translate(%spx, %spx) scale(%s, %s) translate(%spx, %spx); }"
               % (num(px), num(py), num(b["scaleX"]), num(b["scaleY"]), num(-px), num(-py)))
    out.append("}")
    out.append(".ab-breath { animation: ab-breath calc(%dms * var(--ab-speed, 1)) %s infinite alternate; }" % (b["period"] // 2, EASE_IN_OUT))
    out.append("")
    # The hop: take-off (down on its feet, up stretched) and landing
    # (falling stretched, a squash, springing back), about its feet.
    h = bird["motion"]["hop"]
    fx, fy = bird["pivots"]["feet"]

    def squash(pct, sx, sy):
        return "    %s%% { transform: translate(%spx, %spx) scale(%s, %s) translate(%spx, %spx); }" % (
            num(pct), num(fx), num(fy), num(sx), num(sy), num(-fx), num(-fy))
    up = h["takeoff"] + h["rise"]
    out.append("@keyframes ab-takeoff {")
    out.append(squash(0, 1, 1))
    out.append(squash(100 * h["takeoff"] / up, *h["squash"]))
    out.append(squash(100 * (h["takeoff"] + 0.4 * h["rise"]) / up, *h["stretch"]))
    out.append(squash(100, 1, 1))
    out.append("}")
    out.append(".ab-takeoff { animation: ab-takeoff calc(%dms * var(--ab-speed, 1)) ease-out; }" % up)
    down = h["fall"] + h["land"] + h["settle"]
    out.append("@keyframes ab-landing {")
    out.append(squash(0, 1, 1))
    out.append(squash(100 * h["fall"] / down, *h["stretch"]))
    out.append(squash(100 * (h["fall"] + h["land"]) / down, *h["squash"]))
    out.append(squash(100, 1, 1))
    out.append("}")
    out.append(".ab-landing { animation: ab-landing calc(%dms * var(--ab-speed, 1)) ease-in-out; }" % down)
    out.append("")
    # Speaking: the beak in the syllable rhythm (motion.speech), the lower
    # jaw and the mouth from the jaw's top, the upper beak from its edge.
    steps = bird["motion"]["speech"]
    total = sum(ms for _o, ms in steps)
    jx, jy = bird["pivots"]["jaw"]
    ux, uy = bird["pivots"]["upperBeak"]
    usy = bird["beaks"][bird["poses"]["speaking"]["beak"]]["upper"][1]
    for name, (px, py), f in (("jaw", (jx, jy), lambda o: 0.62 + 0.38 * o), ("mouth", (jx, jy), lambda o: o),
                              ("upper", (ux, uy), lambda o: usy + (1 - usy) * (1 - o))):
        out.append("@keyframes ab-talk-%s {" % name)
        t = 0
        out.append("    0%% { transform: translate(%spx, %spx) scale(1, %s) translate(%spx, %spx); }"
                   % (num(px), num(py), num(f(steps[-1][0])), num(-px), num(-py)))
        for o, ms in steps:
            t += ms
            out.append("    %s%% { transform: translate(%spx, %spx) scale(1, %s) translate(%spx, %spx); }"
                       % (num(100 * t / total), num(px), num(py), num(f(o)), num(-px), num(-py)))
        out.append("}")
        out.append(".ab-talk-%s { animation: ab-talk-%s calc(%dms * var(--ab-speed, 1)) ease-in-out infinite; }" % (name, name, total))
    out.append("")
    out.append("@media (prefers-reduced-motion: reduce) {")
    out.append("    .ab-bird * { animation: none !important; transition: none !important; }")
    out.append("}")
    out.append(".ab-bird.ab-still * { animation: none !important; transition: none !important; }")
    return "\n".join(out) + "\n"


def main():
    check = "--check" in sys.argv[1:]
    with open(SOURCE, encoding="utf-8") as f:
        bird = build(json.load(f))
    outputs = {QML_OUT: qml_js(bird), TS_OUT: ts(bird), CSS_OUT: css(bird)}
    stale = []
    for path, text in outputs.items():
        try:
            with open(path, encoding="utf-8") as f:
                same = f.read() == text
        except FileNotFoundError:
            same = False
        if same:
            continue
        if check:
            stale.append(os.path.relpath(path, ROOT))
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
            print("wrote " + os.path.relpath(path, ROOT))
    if stale:
        fail("out of date (run tools/gen-assistant-bird.py): " + ", ".join(stale))


if __name__ == "__main__":
    main()
